/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    AuthoredReviewList,
    CreateReviewBody,
    ErrorResponse,
    ReviewActionResponse,
    UserId,
    UserReviewsView,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Submit a 1-5 star review with an optional comment for a co-traveller of a completed ride
 */
export const getPostReviewsUrl = () => {
    return `/reviews/`;
};

export const postReviews = async (
    createReviewBody: CreateReviewBody,
    options?: RequestInit
): Promise<ReviewActionResponse> => {
    return apiFetcher<ReviewActionResponse>(getPostReviewsUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createReviewBody),
    });
};

export const getPostReviewsMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postReviews>>,
        TError,
        { data: CreateReviewBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postReviews>>,
    TError,
    { data: CreateReviewBody },
    TContext
> => {
    const mutationKey = ["postReviews"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postReviews>>,
        { data: CreateReviewBody }
    > = (props) => {
        const { data } = props ?? {};

        return postReviews(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostReviewsMutationResult = NonNullable<
    Awaited<ReturnType<typeof postReviews>>
>;
export type PostReviewsMutationBody = CreateReviewBody;
export type PostReviewsMutationError = ErrorResponse;

export const usePostReviews = <TError = ErrorResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof postReviews>>,
            TError,
            { data: CreateReviewBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof postReviews>>,
    TError,
    { data: CreateReviewBody },
    TContext
> => {
    const mutationOptions = getPostReviewsMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Returns visible reviews and the average rating for a target user
 */
export const getGetReviewsUsersByUserIdUrl = (userId: UserId) => {
    return `/reviews/users/${userId}`;
};

export const getReviewsUsersByUserId = async (
    userId: UserId,
    options?: RequestInit
): Promise<UserReviewsView> => {
    return apiFetcher<UserReviewsView>(getGetReviewsUsersByUserIdUrl(userId), {
        ...options,
        method: "GET",
    });
};

export const getGetReviewsUsersByUserIdQueryKey = (userId?: UserId) => {
    return [`/reviews/users/${userId}`] as const;
};

export const getGetReviewsUsersByUserIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
    TError = ErrorResponse,
>(
    userId: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetReviewsUsersByUserIdQueryKey(userId);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getReviewsUsersByUserId>>
    > = () => getReviewsUsersByUserId(userId, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!userId,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReviewsUsersByUserIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getReviewsUsersByUserId>>
>;
export type GetReviewsUsersByUserIdQueryError = ErrorResponse;

export function useGetReviewsUsersByUserId<
    TData = Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
    TError = ErrorResponse,
>(
    userId: UserId,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
                    TError,
                    Awaited<ReturnType<typeof getReviewsUsersByUserId>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewsUsersByUserId<
    TData = Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
    TError = ErrorResponse,
>(
    userId: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
                    TError,
                    Awaited<ReturnType<typeof getReviewsUsersByUserId>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewsUsersByUserId<
    TData = Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
    TError = ErrorResponse,
>(
    userId: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetReviewsUsersByUserId<
    TData = Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
    TError = ErrorResponse,
>(
    userId: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsUsersByUserId>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetReviewsUsersByUserIdQueryOptions(
        userId,
        options
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns reviews authored by the current user
 */
export const getGetReviewsMeAuthoredUrl = () => {
    return `/reviews/me/authored`;
};

export const getReviewsMeAuthored = async (
    options?: RequestInit
): Promise<AuthoredReviewList> => {
    return apiFetcher<AuthoredReviewList>(getGetReviewsMeAuthoredUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetReviewsMeAuthoredQueryKey = () => {
    return [`/reviews/me/authored`] as const;
};

export const getGetReviewsMeAuthoredQueryOptions = <
    TData = Awaited<ReturnType<typeof getReviewsMeAuthored>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getReviewsMeAuthored>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetReviewsMeAuthoredQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getReviewsMeAuthored>>
    > = () => getReviewsMeAuthored(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getReviewsMeAuthored>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetReviewsMeAuthoredQueryResult = NonNullable<
    Awaited<ReturnType<typeof getReviewsMeAuthored>>
>;
export type GetReviewsMeAuthoredQueryError = ErrorResponse;

export function useGetReviewsMeAuthored<
    TData = Awaited<ReturnType<typeof getReviewsMeAuthored>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsMeAuthored>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getReviewsMeAuthored>>,
                    TError,
                    Awaited<ReturnType<typeof getReviewsMeAuthored>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewsMeAuthored<
    TData = Awaited<ReturnType<typeof getReviewsMeAuthored>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsMeAuthored>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getReviewsMeAuthored>>,
                    TError,
                    Awaited<ReturnType<typeof getReviewsMeAuthored>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetReviewsMeAuthored<
    TData = Awaited<ReturnType<typeof getReviewsMeAuthored>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsMeAuthored>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetReviewsMeAuthored<
    TData = Awaited<ReturnType<typeof getReviewsMeAuthored>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getReviewsMeAuthored>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetReviewsMeAuthoredQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}
