/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    AvailableRideList,
    CancelRideBody,
    CancelRideResponse,
    CompleteRideBody,
    CompleteRideResponse,
    CreateRideBody,
    CreateRideResponse,
    EndRideBody,
    EndRideResponse,
    ErrorResponse,
    GetRidesMeParams,
    GetRidesSearchParams,
    RideId,
    RideListItemList,
    RidePassengersView,
    RideSearchResultList,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns upcoming planned rides available for booking
 */
export const getGetRidesAvailableUrl = () => {
    return `/rides/available`;
};

export const getRidesAvailable = async (
    options?: RequestInit
): Promise<AvailableRideList> => {
    return apiFetcher<AvailableRideList>(getGetRidesAvailableUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetRidesAvailableQueryKey = () => {
    return [`/rides/available`] as const;
};

export const getGetRidesAvailableQueryOptions = <
    TData = Awaited<ReturnType<typeof getRidesAvailable>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getRidesAvailable>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetRidesAvailableQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getRidesAvailable>>
    > = () => getRidesAvailable(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getRidesAvailable>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRidesAvailableQueryResult = NonNullable<
    Awaited<ReturnType<typeof getRidesAvailable>>
>;
export type GetRidesAvailableQueryError = ErrorResponse;

export function useGetRidesAvailable<
    TData = Awaited<ReturnType<typeof getRidesAvailable>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesAvailable>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRidesAvailable>>,
                    TError,
                    Awaited<ReturnType<typeof getRidesAvailable>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRidesAvailable<
    TData = Awaited<ReturnType<typeof getRidesAvailable>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesAvailable>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRidesAvailable>>,
                    TError,
                    Awaited<ReturnType<typeof getRidesAvailable>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRidesAvailable<
    TData = Awaited<ReturnType<typeof getRidesAvailable>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesAvailable>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetRidesAvailable<
    TData = Awaited<ReturnType<typeof getRidesAvailable>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesAvailable>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetRidesAvailableQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Search rides between two cities on a specific date
 */
export const getGetRidesSearchUrl = (params: GetRidesSearchParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/rides/search?${stringifiedParams}`
        : `/rides/search`;
};

export const getRidesSearch = async (
    params: GetRidesSearchParams,
    options?: RequestInit
): Promise<RideSearchResultList> => {
    return apiFetcher<RideSearchResultList>(getGetRidesSearchUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetRidesSearchQueryKey = (params?: GetRidesSearchParams) => {
    return [`/rides/search`, ...(params ? [params] : [])] as const;
};

export const getGetRidesSearchQueryOptions = <
    TData = Awaited<ReturnType<typeof getRidesSearch>>,
    TError = ErrorResponse,
>(
    params: GetRidesSearchParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesSearch>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetRidesSearchQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getRidesSearch>>
    > = () => getRidesSearch(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getRidesSearch>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRidesSearchQueryResult = NonNullable<
    Awaited<ReturnType<typeof getRidesSearch>>
>;
export type GetRidesSearchQueryError = ErrorResponse;

export function useGetRidesSearch<
    TData = Awaited<ReturnType<typeof getRidesSearch>>,
    TError = ErrorResponse,
>(
    params: GetRidesSearchParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesSearch>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRidesSearch>>,
                    TError,
                    Awaited<ReturnType<typeof getRidesSearch>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRidesSearch<
    TData = Awaited<ReturnType<typeof getRidesSearch>>,
    TError = ErrorResponse,
>(
    params: GetRidesSearchParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesSearch>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRidesSearch>>,
                    TError,
                    Awaited<ReturnType<typeof getRidesSearch>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRidesSearch<
    TData = Awaited<ReturnType<typeof getRidesSearch>>,
    TError = ErrorResponse,
>(
    params: GetRidesSearchParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesSearch>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetRidesSearch<
    TData = Awaited<ReturnType<typeof getRidesSearch>>,
    TError = ErrorResponse,
>(
    params: GetRidesSearchParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesSearch>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetRidesSearchQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns rides created by the authenticated driver
 */
export const getGetRidesMeUrl = (params: GetRidesMeParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/rides/me?${stringifiedParams}`
        : `/rides/me`;
};

export const getRidesMe = async (
    params: GetRidesMeParams,
    options?: RequestInit
): Promise<RideListItemList> => {
    return apiFetcher<RideListItemList>(getGetRidesMeUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetRidesMeQueryKey = (params?: GetRidesMeParams) => {
    return [`/rides/me`, ...(params ? [params] : [])] as const;
};

export const getGetRidesMeQueryOptions = <
    TData = Awaited<ReturnType<typeof getRidesMe>>,
    TError = ErrorResponse,
>(
    params: GetRidesMeParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesMe>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetRidesMeQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getRidesMe>>> = () =>
        getRidesMe(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getRidesMe>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRidesMeQueryResult = NonNullable<
    Awaited<ReturnType<typeof getRidesMe>>
>;
export type GetRidesMeQueryError = ErrorResponse;

export function useGetRidesMe<
    TData = Awaited<ReturnType<typeof getRidesMe>>,
    TError = ErrorResponse,
>(
    params: GetRidesMeParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesMe>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRidesMe>>,
                    TError,
                    Awaited<ReturnType<typeof getRidesMe>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRidesMe<
    TData = Awaited<ReturnType<typeof getRidesMe>>,
    TError = ErrorResponse,
>(
    params: GetRidesMeParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesMe>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRidesMe>>,
                    TError,
                    Awaited<ReturnType<typeof getRidesMe>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRidesMe<
    TData = Awaited<ReturnType<typeof getRidesMe>>,
    TError = ErrorResponse,
>(
    params: GetRidesMeParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesMe>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetRidesMe<
    TData = Awaited<ReturnType<typeof getRidesMe>>,
    TError = ErrorResponse,
>(
    params: GetRidesMeParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesMe>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetRidesMeQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Creates a new ride as a driver
 */
export const getPostRidesUrl = () => {
    return `/rides/`;
};

export const postRides = async (
    createRideBody: CreateRideBody,
    options?: RequestInit
): Promise<CreateRideResponse> => {
    return apiFetcher<CreateRideResponse>(getPostRidesUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createRideBody),
    });
};

export const getPostRidesMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postRides>>,
        TError,
        { data: CreateRideBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postRides>>,
    TError,
    { data: CreateRideBody },
    TContext
> => {
    const mutationKey = ["postRides"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postRides>>,
        { data: CreateRideBody }
    > = (props) => {
        const { data } = props ?? {};

        return postRides(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostRidesMutationResult = NonNullable<
    Awaited<ReturnType<typeof postRides>>
>;
export type PostRidesMutationBody = CreateRideBody;
export type PostRidesMutationError = ErrorResponse;

export const usePostRides = <TError = ErrorResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof postRides>>,
            TError,
            { data: CreateRideBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof postRides>>,
    TError,
    { data: CreateRideBody },
    TContext
> => {
    const mutationOptions = getPostRidesMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Returns ride details including all confirmed passengers
 */
export const getGetRidesByIdPassengersUrl = (id: RideId) => {
    return `/rides/${id}/passengers`;
};

export const getRidesByIdPassengers = async (
    id: RideId,
    options?: RequestInit
): Promise<RidePassengersView> => {
    return apiFetcher<RidePassengersView>(getGetRidesByIdPassengersUrl(id), {
        ...options,
        method: "GET",
    });
};

export const getGetRidesByIdPassengersQueryKey = (id?: RideId) => {
    return [`/rides/${id}/passengers`] as const;
};

export const getGetRidesByIdPassengersQueryOptions = <
    TData = Awaited<ReturnType<typeof getRidesByIdPassengers>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesByIdPassengers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetRidesByIdPassengersQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getRidesByIdPassengers>>
    > = () => getRidesByIdPassengers(id, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getRidesByIdPassengers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetRidesByIdPassengersQueryResult = NonNullable<
    Awaited<ReturnType<typeof getRidesByIdPassengers>>
>;
export type GetRidesByIdPassengersQueryError = ErrorResponse;

export function useGetRidesByIdPassengers<
    TData = Awaited<ReturnType<typeof getRidesByIdPassengers>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesByIdPassengers>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRidesByIdPassengers>>,
                    TError,
                    Awaited<ReturnType<typeof getRidesByIdPassengers>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRidesByIdPassengers<
    TData = Awaited<ReturnType<typeof getRidesByIdPassengers>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesByIdPassengers>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getRidesByIdPassengers>>,
                    TError,
                    Awaited<ReturnType<typeof getRidesByIdPassengers>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetRidesByIdPassengers<
    TData = Awaited<ReturnType<typeof getRidesByIdPassengers>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesByIdPassengers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetRidesByIdPassengers<
    TData = Awaited<ReturnType<typeof getRidesByIdPassengers>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getRidesByIdPassengers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetRidesByIdPassengersQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Cancels a ride and cascades cancellation to all active passenger bookings
 */
export const getPatchRidesByIdCancelUrl = (id: RideId) => {
    return `/rides/${id}/cancel`;
};

export const patchRidesByIdCancel = async (
    id: RideId,
    cancelRideBody: CancelRideBody,
    options?: RequestInit
): Promise<CancelRideResponse> => {
    return apiFetcher<CancelRideResponse>(getPatchRidesByIdCancelUrl(id), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(cancelRideBody),
    });
};

export const getPatchRidesByIdCancelMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchRidesByIdCancel>>,
        TError,
        { id: RideId; data: CancelRideBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchRidesByIdCancel>>,
    TError,
    { id: RideId; data: CancelRideBody },
    TContext
> => {
    const mutationKey = ["patchRidesByIdCancel"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchRidesByIdCancel>>,
        { id: RideId; data: CancelRideBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchRidesByIdCancel(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchRidesByIdCancelMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchRidesByIdCancel>>
>;
export type PatchRidesByIdCancelMutationBody = CancelRideBody;
export type PatchRidesByIdCancelMutationError = ErrorResponse;

export const usePatchRidesByIdCancel = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchRidesByIdCancel>>,
            TError,
            { id: RideId; data: CancelRideBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchRidesByIdCancel>>,
    TError,
    { id: RideId; data: CancelRideBody },
    TContext
> => {
    const mutationOptions = getPatchRidesByIdCancelMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Ends the driver's ride idempotently and records ride end metadata
 */
export const getPatchRidesByIdEndUrl = (id: RideId) => {
    return `/rides/${id}/end`;
};

export const patchRidesByIdEnd = async (
    id: RideId,
    endRideBody: EndRideBody,
    options?: RequestInit
): Promise<EndRideResponse> => {
    return apiFetcher<EndRideResponse>(getPatchRidesByIdEndUrl(id), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(endRideBody),
    });
};

export const getPatchRidesByIdEndMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchRidesByIdEnd>>,
        TError,
        { id: RideId; data: EndRideBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchRidesByIdEnd>>,
    TError,
    { id: RideId; data: EndRideBody },
    TContext
> => {
    const mutationKey = ["patchRidesByIdEnd"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchRidesByIdEnd>>,
        { id: RideId; data: EndRideBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchRidesByIdEnd(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchRidesByIdEndMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchRidesByIdEnd>>
>;
export type PatchRidesByIdEndMutationBody = EndRideBody;
export type PatchRidesByIdEndMutationError = ErrorResponse;

export const usePatchRidesByIdEnd = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchRidesByIdEnd>>,
            TError,
            { id: RideId; data: EndRideBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchRidesByIdEnd>>,
    TError,
    { id: RideId; data: EndRideBody },
    TContext
> => {
    const mutationOptions = getPatchRidesByIdEndMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Marks the driver's ride as COMPLETED and carries confirmed bookings to COMPLETED, opening the review window
 */
export const getPatchRidesByIdCompleteUrl = (id: RideId) => {
    return `/rides/${id}/complete`;
};

export const patchRidesByIdComplete = async (
    id: RideId,
    completeRideBody: CompleteRideBody,
    options?: RequestInit
): Promise<CompleteRideResponse> => {
    return apiFetcher<CompleteRideResponse>(getPatchRidesByIdCompleteUrl(id), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(completeRideBody),
    });
};

export const getPatchRidesByIdCompleteMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchRidesByIdComplete>>,
        TError,
        { id: RideId; data: CompleteRideBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchRidesByIdComplete>>,
    TError,
    { id: RideId; data: CompleteRideBody },
    TContext
> => {
    const mutationKey = ["patchRidesByIdComplete"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchRidesByIdComplete>>,
        { id: RideId; data: CompleteRideBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchRidesByIdComplete(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchRidesByIdCompleteMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchRidesByIdComplete>>
>;
export type PatchRidesByIdCompleteMutationBody = CompleteRideBody;
export type PatchRidesByIdCompleteMutationError = ErrorResponse;

export const usePatchRidesByIdComplete = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchRidesByIdComplete>>,
            TError,
            { id: RideId; data: CompleteRideBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchRidesByIdComplete>>,
    TError,
    { id: RideId; data: CompleteRideBody },
    TContext
> => {
    const mutationOptions = getPatchRidesByIdCompleteMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
