/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation } from "@tanstack/react-query";
import type {
    MutationFunction,
    QueryClient,
    UseMutationOptions,
    UseMutationResult,
} from "@tanstack/react-query";

import type {
    CreateReportBody,
    ErrorResponse,
    ReportActionResponse,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * File a moderation report against another user. The reporter must share at least one ride with the target (driver↔passenger, in either direction). Optional rideId carries the context the report was filed from.
 */
export const getPostReportsUrl = () => {
    return `/reports/`;
};

export const postReports = async (
    createReportBody: CreateReportBody,
    options?: RequestInit
): Promise<ReportActionResponse> => {
    return apiFetcher<ReportActionResponse>(getPostReportsUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createReportBody),
    });
};

export const getPostReportsMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postReports>>,
        TError,
        { data: CreateReportBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postReports>>,
    TError,
    { data: CreateReportBody },
    TContext
> => {
    const mutationKey = ["postReports"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postReports>>,
        { data: CreateReportBody }
    > = (props) => {
        const { data } = props ?? {};

        return postReports(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostReportsMutationResult = NonNullable<
    Awaited<ReturnType<typeof postReports>>
>;
export type PostReportsMutationBody = CreateReportBody;
export type PostReportsMutationError = ErrorResponse;

export const usePostReports = <TError = ErrorResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof postReports>>,
            TError,
            { data: CreateReportBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof postReports>>,
    TError,
    { data: CreateReportBody },
    TContext
> => {
    const mutationOptions = getPostReportsMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
