variables:
    PIPELINE_NAME: "Waymate CI"

workflow:
    name: $PIPELINE_NAME
    rules:
        - if: $CI_COMMIT_BRANCH && $CI_OPEN_MERGE_REQUESTS && $CI_PIPELINE_SOURCE == "push"
          when: never
        - if: $CI_PIPELINE_SOURCE == "merge_request_event"
          variables:
              PIPELINE_NAME: "Waymate MR Pipeline"
        - if: $CI_PIPELINE_SOURCE == "push"
          variables:
              PIPELINE_NAME: "Waymate Branch Pipeline"

stages:
    - verify

default:
    image: oven/bun:1.3.10
    tags:
        - shared-fi
    cache:
        key: ${CI_COMMIT_REF_SLUG}
        paths:
            - .bun/install/cache
    before_script:
        - echo "//gitlab.fi.muni.cz/api/v4/projects/48090/packages/npm/:_authToken=${CI_JOB_TOKEN}" >> ~/.npmrc
        - bun --version
        - bun install

generate-lockfile:
    stage: verify
    script:
        - echo "lockfile generated"
    artifacts:
        paths:
            - bun.lock
        expire_in: 1 day

lint:
    stage: verify
    script:
        - bun run lint

format:
    stage: verify
    script:
        - bun run format:check

typecheck:
    stage: verify
    script:
        - bun run typecheck

build:
    stage: verify
    script:
        - bun run build
