/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    AdminCancelRideBody,
    AdminCancelRideResponse,
    AdminDeleteReviewResponse,
    AdminReportDetailResponse,
    AdminReportListResponse,
    AdminReviewCounts,
    AdminReviewDetailResponse,
    AdminReviewListItem,
    AdminReviewListResponse,
    AdminRideDetailResponse,
    AdminRideListResponse,
    AdminUserDetailResponse,
    AdminUserListItem,
    AdminUserListResponse,
    ErrorResponse,
    GetAdminReportsParams,
    GetAdminReviewsParams,
    GetAdminRidesParams,
    GetAdminUsersParams,
    ReportId,
    ReviewId,
    RideId,
    UpdateReportStatusBody,
    UpdateReviewStatusBody,
    UpdateUserStatusBody,
    UserId,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns a keyset-paginated list of users for admin tooling. Supports a case-insensitive substring search across email, firstName, lastName.
 */
export const getGetAdminUsersUrl = (params: GetAdminUsersParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/admin/users?${stringifiedParams}`
        : `/admin/users`;
};

export const getAdminUsers = async (
    params: GetAdminUsersParams,
    options?: RequestInit
): Promise<AdminUserListResponse> => {
    return apiFetcher<AdminUserListResponse>(getGetAdminUsersUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminUsersQueryKey = (params?: GetAdminUsersParams) => {
    return [`/admin/users`, ...(params ? [params] : [])] as const;
};

export const getGetAdminUsersQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAdminUsersQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminUsers>>
    > = () => getAdminUsers(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUsers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminUsersQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminUsers>>
>;
export type GetAdminUsersQueryError = ErrorResponse;

export function useGetAdminUsers<
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminUsers>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminUsers>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUsers<
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminUsers>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminUsers>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUsers<
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminUsers<
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminUsersQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns full user detail plus the most recent status history entries (newest first, capped at 50). changedBy is null for system-triggered changes or when the actor admin no longer exists.
 */
export const getGetAdminUsersByIdUrl = (id: UserId) => {
    return `/admin/users/${id}`;
};

export const getAdminUsersById = async (
    id: UserId,
    options?: RequestInit
): Promise<AdminUserDetailResponse> => {
    return apiFetcher<AdminUserDetailResponse>(getGetAdminUsersByIdUrl(id), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminUsersByIdQueryKey = (id?: UserId) => {
    return [`/admin/users/${id}`] as const;
};

export const getGetAdminUsersByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAdminUsersByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminUsersById>>
    > = () => getAdminUsersById(id, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUsersById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminUsersByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminUsersById>>
>;
export type GetAdminUsersByIdQueryError = ErrorResponse;

export function useGetAdminUsersById<
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminUsersById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminUsersById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUsersById<
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminUsersById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminUsersById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUsersById<
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminUsersById<
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminUsersByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Changes a user's account status (ACTIVE / SUSPENDED / BANNED / DELETED) and records an audit row in user_status_history.
 */
export const getPatchAdminUsersByIdStatusUrl = (id: UserId) => {
    return `/admin/users/${id}/status`;
};

export const patchAdminUsersByIdStatus = async (
    id: UserId,
    updateUserStatusBody: UpdateUserStatusBody,
    options?: RequestInit
): Promise<AdminUserListItem> => {
    return apiFetcher<AdminUserListItem>(getPatchAdminUsersByIdStatusUrl(id), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(updateUserStatusBody),
    });
};

export const getPatchAdminUsersByIdStatusMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
        TError,
        { id: UserId; data: UpdateUserStatusBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
    TError,
    { id: UserId; data: UpdateUserStatusBody },
    TContext
> => {
    const mutationKey = ["patchAdminUsersByIdStatus"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
        { id: UserId; data: UpdateUserStatusBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchAdminUsersByIdStatus(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchAdminUsersByIdStatusMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>
>;
export type PatchAdminUsersByIdStatusMutationBody = UpdateUserStatusBody;
export type PatchAdminUsersByIdStatusMutationError = ErrorResponse;

export const usePatchAdminUsersByIdStatus = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
            TError,
            { id: UserId; data: UpdateUserStatusBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
    TError,
    { id: UserId; data: UpdateUserStatusBody },
    TContext
> => {
    const mutationOptions =
        getPatchAdminUsersByIdStatusMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Returns a keyset-paginated list of rides for admin tooling. Supports filtering by status and case-insensitive driver email/firstName/lastName search.
 */
export const getGetAdminRidesUrl = (params: GetAdminRidesParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/admin/rides?${stringifiedParams}`
        : `/admin/rides`;
};

export const getAdminRides = async (
    params: GetAdminRidesParams,
    options?: RequestInit
): Promise<AdminRideListResponse> => {
    return apiFetcher<AdminRideListResponse>(getGetAdminRidesUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminRidesQueryKey = (params?: GetAdminRidesParams) => {
    return [`/admin/rides`, ...(params ? [params] : [])] as const;
};

export const getGetAdminRidesQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminRides>>,
    TError = ErrorResponse,
>(
    params: GetAdminRidesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRides>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAdminRidesQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminRides>>
    > = () => getAdminRides(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRides>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminRidesQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminRides>>
>;
export type GetAdminRidesQueryError = ErrorResponse;

export function useGetAdminRides<
    TData = Awaited<ReturnType<typeof getAdminRides>>,
    TError = ErrorResponse,
>(
    params: GetAdminRidesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRides>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminRides>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminRides>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminRides<
    TData = Awaited<ReturnType<typeof getAdminRides>>,
    TError = ErrorResponse,
>(
    params: GetAdminRidesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRides>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminRides>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminRides>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminRides<
    TData = Awaited<ReturnType<typeof getAdminRides>>,
    TError = ErrorResponse,
>(
    params: GetAdminRidesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRides>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminRides<
    TData = Awaited<ReturnType<typeof getAdminRides>>,
    TError = ErrorResponse,
>(
    params: GetAdminRidesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRides>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminRidesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns full ride detail (driver, car, stops, prices, bookings) plus the most recent status history entries (newest first, capped at 50). changedBy is null for system-triggered changes.
 */
export const getGetAdminRidesByIdUrl = (id: RideId) => {
    return `/admin/rides/${id}`;
};

export const getAdminRidesById = async (
    id: RideId,
    options?: RequestInit
): Promise<AdminRideDetailResponse> => {
    return apiFetcher<AdminRideDetailResponse>(getGetAdminRidesByIdUrl(id), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminRidesByIdQueryKey = (id?: RideId) => {
    return [`/admin/rides/${id}`] as const;
};

export const getGetAdminRidesByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminRidesById>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRidesById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAdminRidesByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminRidesById>>
    > = () => getAdminRidesById(id, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminRidesById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminRidesByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminRidesById>>
>;
export type GetAdminRidesByIdQueryError = ErrorResponse;

export function useGetAdminRidesById<
    TData = Awaited<ReturnType<typeof getAdminRidesById>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRidesById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminRidesById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminRidesById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminRidesById<
    TData = Awaited<ReturnType<typeof getAdminRidesById>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRidesById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminRidesById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminRidesById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminRidesById<
    TData = Awaited<ReturnType<typeof getAdminRidesById>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRidesById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminRidesById<
    TData = Awaited<ReturnType<typeof getAdminRidesById>>,
    TError = ErrorResponse,
>(
    id: RideId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminRidesById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminRidesByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns a keyset-paginated list of reviews for moderation. Supports filtering by status, rating range, and case-insensitive search across comment text and author/subject email/name.
 */
export const getGetAdminReviewsUrl = (params: GetAdminReviewsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/admin/reviews?${stringifiedParams}`
        : `/admin/reviews`;
};

export const getAdminReviews = async (
    params: GetAdminReviewsParams,
    options?: RequestInit
): Promise<AdminReviewListResponse> => {
    return apiFetcher<AdminReviewListResponse>(getGetAdminReviewsUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminReviewsQueryKey = (params?: GetAdminReviewsParams) => {
    return [`/admin/reviews`, ...(params ? [params] : [])] as const;
};

export const getGetAdminReviewsQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminReviews>>,
    TError = ErrorResponse,
>(
    params: GetAdminReviewsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviews>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetAdminReviewsQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminReviews>>
    > = () => getAdminReviews(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminReviews>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminReviewsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminReviews>>
>;
export type GetAdminReviewsQueryError = ErrorResponse;

export function useGetAdminReviews<
    TData = Awaited<ReturnType<typeof getAdminReviews>>,
    TError = ErrorResponse,
>(
    params: GetAdminReviewsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviews>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReviews>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReviews>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReviews<
    TData = Awaited<ReturnType<typeof getAdminReviews>>,
    TError = ErrorResponse,
>(
    params: GetAdminReviewsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviews>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReviews>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReviews>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReviews<
    TData = Awaited<ReturnType<typeof getAdminReviews>>,
    TError = ErrorResponse,
>(
    params: GetAdminReviewsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviews>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminReviews<
    TData = Awaited<ReturnType<typeof getAdminReviews>>,
    TError = ErrorResponse,
>(
    params: GetAdminReviewsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviews>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminReviewsQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns counts of non-deleted reviews grouped by status (all, visible, hidden) for admin tab badges.
 */
export const getGetAdminReviewsCountsUrl = () => {
    return `/admin/reviews/counts`;
};

export const getAdminReviewsCounts = async (
    options?: RequestInit
): Promise<AdminReviewCounts> => {
    return apiFetcher<AdminReviewCounts>(getGetAdminReviewsCountsUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminReviewsCountsQueryKey = () => {
    return [`/admin/reviews/counts`] as const;
};

export const getGetAdminReviewsCountsQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminReviewsCounts>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getAdminReviewsCounts>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetAdminReviewsCountsQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminReviewsCounts>>
    > = () => getAdminReviewsCounts(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminReviewsCounts>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminReviewsCountsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminReviewsCounts>>
>;
export type GetAdminReviewsCountsQueryError = ErrorResponse;

export function useGetAdminReviewsCounts<
    TData = Awaited<ReturnType<typeof getAdminReviewsCounts>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsCounts>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReviewsCounts>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReviewsCounts>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReviewsCounts<
    TData = Awaited<ReturnType<typeof getAdminReviewsCounts>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsCounts>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReviewsCounts>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReviewsCounts>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReviewsCounts<
    TData = Awaited<ReturnType<typeof getAdminReviewsCounts>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsCounts>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminReviewsCounts<
    TData = Awaited<ReturnType<typeof getAdminReviewsCounts>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsCounts>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminReviewsCountsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Permanently soft-deletes a review. The review is removed from all public surfaces and excluded from rating aggregates.
 */
export const getDeleteAdminReviewsByIdUrl = (id: ReviewId) => {
    return `/admin/reviews/${id}`;
};

export const deleteAdminReviewsById = async (
    id: ReviewId,
    options?: RequestInit
): Promise<AdminDeleteReviewResponse> => {
    return apiFetcher<AdminDeleteReviewResponse>(
        getDeleteAdminReviewsByIdUrl(id),
        {
            ...options,
            method: "DELETE",
        }
    );
};

export const getDeleteAdminReviewsByIdMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteAdminReviewsById>>,
        TError,
        { id: ReviewId },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteAdminReviewsById>>,
    TError,
    { id: ReviewId },
    TContext
> => {
    const mutationKey = ["deleteAdminReviewsById"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteAdminReviewsById>>,
        { id: ReviewId }
    > = (props) => {
        const { id } = props ?? {};

        return deleteAdminReviewsById(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteAdminReviewsByIdMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteAdminReviewsById>>
>;

export type DeleteAdminReviewsByIdMutationError = ErrorResponse;

export const useDeleteAdminReviewsById = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteAdminReviewsById>>,
            TError,
            { id: ReviewId },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof deleteAdminReviewsById>>,
    TError,
    { id: ReviewId },
    TContext
> => {
    const mutationOptions = getDeleteAdminReviewsByIdMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Returns full review detail (author, subject, ride context) plus the most recent status history entries (newest first, capped at 50).
 */
export const getGetAdminReviewsByIdUrl = (id: ReviewId) => {
    return `/admin/reviews/${id}`;
};

export const getAdminReviewsById = async (
    id: ReviewId,
    options?: RequestInit
): Promise<AdminReviewDetailResponse> => {
    return apiFetcher<AdminReviewDetailResponse>(
        getGetAdminReviewsByIdUrl(id),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getGetAdminReviewsByIdQueryKey = (id?: ReviewId) => {
    return [`/admin/reviews/${id}`] as const;
};

export const getGetAdminReviewsByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminReviewsById>>,
    TError = ErrorResponse,
>(
    id: ReviewId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetAdminReviewsByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminReviewsById>>
    > = () => getAdminReviewsById(id, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminReviewsById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminReviewsByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminReviewsById>>
>;
export type GetAdminReviewsByIdQueryError = ErrorResponse;

export function useGetAdminReviewsById<
    TData = Awaited<ReturnType<typeof getAdminReviewsById>>,
    TError = ErrorResponse,
>(
    id: ReviewId,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReviewsById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReviewsById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReviewsById<
    TData = Awaited<ReturnType<typeof getAdminReviewsById>>,
    TError = ErrorResponse,
>(
    id: ReviewId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReviewsById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReviewsById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReviewsById<
    TData = Awaited<ReturnType<typeof getAdminReviewsById>>,
    TError = ErrorResponse,
>(
    id: ReviewId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminReviewsById<
    TData = Awaited<ReturnType<typeof getAdminReviewsById>>,
    TError = ErrorResponse,
>(
    id: ReviewId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReviewsById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminReviewsByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Changes a review's moderation status (VISIBLE / HIDDEN / REMOVED) and records an audit row in review_status_history. The reason is required so the moderation log makes the action traceable.
 */
export const getPatchAdminReviewsByIdStatusUrl = (id: ReviewId) => {
    return `/admin/reviews/${id}/status`;
};

export const patchAdminReviewsByIdStatus = async (
    id: ReviewId,
    updateReviewStatusBody: UpdateReviewStatusBody,
    options?: RequestInit
): Promise<AdminReviewListItem> => {
    return apiFetcher<AdminReviewListItem>(
        getPatchAdminReviewsByIdStatusUrl(id),
        {
            ...options,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(updateReviewStatusBody),
        }
    );
};

export const getPatchAdminReviewsByIdStatusMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchAdminReviewsByIdStatus>>,
        TError,
        { id: ReviewId; data: UpdateReviewStatusBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchAdminReviewsByIdStatus>>,
    TError,
    { id: ReviewId; data: UpdateReviewStatusBody },
    TContext
> => {
    const mutationKey = ["patchAdminReviewsByIdStatus"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchAdminReviewsByIdStatus>>,
        { id: ReviewId; data: UpdateReviewStatusBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchAdminReviewsByIdStatus(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchAdminReviewsByIdStatusMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchAdminReviewsByIdStatus>>
>;
export type PatchAdminReviewsByIdStatusMutationBody = UpdateReviewStatusBody;
export type PatchAdminReviewsByIdStatusMutationError = ErrorResponse;

export const usePatchAdminReviewsByIdStatus = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchAdminReviewsByIdStatus>>,
            TError,
            { id: ReviewId; data: UpdateReviewStatusBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchAdminReviewsByIdStatus>>,
    TError,
    { id: ReviewId; data: UpdateReviewStatusBody },
    TContext
> => {
    const mutationOptions =
        getPatchAdminReviewsByIdStatusMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Force-cancels a ride as admin and cascades cancellation to all active passenger bookings (PENDING/CONFIRMED). Records an audit row in ride_status_history with the admin as changedByUserId. The reason is required so the audit log makes the override traceable.
 */
export const getPatchAdminRidesByIdCancelUrl = (id: RideId) => {
    return `/admin/rides/${id}/cancel`;
};

export const patchAdminRidesByIdCancel = async (
    id: RideId,
    adminCancelRideBody: AdminCancelRideBody,
    options?: RequestInit
): Promise<AdminCancelRideResponse> => {
    return apiFetcher<AdminCancelRideResponse>(
        getPatchAdminRidesByIdCancelUrl(id),
        {
            ...options,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(adminCancelRideBody),
        }
    );
};

export const getPatchAdminRidesByIdCancelMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchAdminRidesByIdCancel>>,
        TError,
        { id: RideId; data: AdminCancelRideBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchAdminRidesByIdCancel>>,
    TError,
    { id: RideId; data: AdminCancelRideBody },
    TContext
> => {
    const mutationKey = ["patchAdminRidesByIdCancel"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchAdminRidesByIdCancel>>,
        { id: RideId; data: AdminCancelRideBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchAdminRidesByIdCancel(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchAdminRidesByIdCancelMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchAdminRidesByIdCancel>>
>;
export type PatchAdminRidesByIdCancelMutationBody = AdminCancelRideBody;
export type PatchAdminRidesByIdCancelMutationError = ErrorResponse;

export const usePatchAdminRidesByIdCancel = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchAdminRidesByIdCancel>>,
            TError,
            { id: RideId; data: AdminCancelRideBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchAdminRidesByIdCancel>>,
    TError,
    { id: RideId; data: AdminCancelRideBody },
    TContext
> => {
    const mutationOptions =
        getPatchAdminRidesByIdCancelMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Returns a keyset-paginated list of user reports for moderation. Supports filtering by status, type, and case-insensitive search across description and reporter/target email/name.
 */
export const getGetAdminReportsUrl = (params: GetAdminReportsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/admin/reports?${stringifiedParams}`
        : `/admin/reports`;
};

export const getAdminReports = async (
    params: GetAdminReportsParams,
    options?: RequestInit
): Promise<AdminReportListResponse> => {
    return apiFetcher<AdminReportListResponse>(getGetAdminReportsUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminReportsQueryKey = (params?: GetAdminReportsParams) => {
    return [`/admin/reports`, ...(params ? [params] : [])] as const;
};

export const getGetAdminReportsQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminReports>>,
    TError = ErrorResponse,
>(
    params: GetAdminReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReports>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetAdminReportsQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminReports>>
    > = () => getAdminReports(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminReports>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminReportsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminReports>>
>;
export type GetAdminReportsQueryError = ErrorResponse;

export function useGetAdminReports<
    TData = Awaited<ReturnType<typeof getAdminReports>>,
    TError = ErrorResponse,
>(
    params: GetAdminReportsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReports>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReports>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReports>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReports<
    TData = Awaited<ReturnType<typeof getAdminReports>>,
    TError = ErrorResponse,
>(
    params: GetAdminReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReports>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReports>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReports>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReports<
    TData = Awaited<ReturnType<typeof getAdminReports>>,
    TError = ErrorResponse,
>(
    params: GetAdminReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReports>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminReports<
    TData = Awaited<ReturnType<typeof getAdminReports>>,
    TError = ErrorResponse,
>(
    params: GetAdminReportsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReports>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminReportsQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns full report detail (reporter, target, ride context if present, resolution reason) plus the status history (newest first, capped at 50).
 */
export const getGetAdminReportsByIdUrl = (id: ReportId) => {
    return `/admin/reports/${id}`;
};

export const getAdminReportsById = async (
    id: ReportId,
    options?: RequestInit
): Promise<AdminReportDetailResponse> => {
    return apiFetcher<AdminReportDetailResponse>(
        getGetAdminReportsByIdUrl(id),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getGetAdminReportsByIdQueryKey = (id?: ReportId) => {
    return [`/admin/reports/${id}`] as const;
};

export const getGetAdminReportsByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminReportsById>>,
    TError = ErrorResponse,
>(
    id: ReportId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReportsById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetAdminReportsByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminReportsById>>
    > = () => getAdminReportsById(id, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminReportsById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminReportsByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminReportsById>>
>;
export type GetAdminReportsByIdQueryError = ErrorResponse;

export function useGetAdminReportsById<
    TData = Awaited<ReturnType<typeof getAdminReportsById>>,
    TError = ErrorResponse,
>(
    id: ReportId,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReportsById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReportsById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReportsById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReportsById<
    TData = Awaited<ReturnType<typeof getAdminReportsById>>,
    TError = ErrorResponse,
>(
    id: ReportId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReportsById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminReportsById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminReportsById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminReportsById<
    TData = Awaited<ReturnType<typeof getAdminReportsById>>,
    TError = ErrorResponse,
>(
    id: ReportId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReportsById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminReportsById<
    TData = Awaited<ReturnType<typeof getAdminReportsById>>,
    TError = ErrorResponse,
>(
    id: ReportId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminReportsById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminReportsByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Moves a report through its workflow: OPEN→INVESTIGATING (no reason), OPEN/INVESTIGATING→RESOLVED or DISMISSED (reason required). RESOLVED and DISMISSED are terminal. Records an audit row in report_status_history with the admin as changedByUserId.
 */
export const getPatchAdminReportsByIdStatusUrl = (id: ReportId) => {
    return `/admin/reports/${id}/status`;
};

export const patchAdminReportsByIdStatus = async (
    id: ReportId,
    updateReportStatusBody: UpdateReportStatusBody,
    options?: RequestInit
): Promise<AdminReportDetailResponse> => {
    return apiFetcher<AdminReportDetailResponse>(
        getPatchAdminReportsByIdStatusUrl(id),
        {
            ...options,
            method: "PATCH",
            headers: {
                "Content-Type": "application/json",
                ...options?.headers,
            },
            body: JSON.stringify(updateReportStatusBody),
        }
    );
};

export const getPatchAdminReportsByIdStatusMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchAdminReportsByIdStatus>>,
        TError,
        { id: ReportId; data: UpdateReportStatusBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchAdminReportsByIdStatus>>,
    TError,
    { id: ReportId; data: UpdateReportStatusBody },
    TContext
> => {
    const mutationKey = ["patchAdminReportsByIdStatus"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchAdminReportsByIdStatus>>,
        { id: ReportId; data: UpdateReportStatusBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchAdminReportsByIdStatus(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchAdminReportsByIdStatusMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchAdminReportsByIdStatus>>
>;
export type PatchAdminReportsByIdStatusMutationBody = UpdateReportStatusBody;
export type PatchAdminReportsByIdStatusMutationError = ErrorResponse;

export const usePatchAdminReportsByIdStatus = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchAdminReportsByIdStatus>>,
            TError,
            { id: ReportId; data: UpdateReportStatusBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchAdminReportsByIdStatus>>,
    TError,
    { id: ReportId; data: UpdateReportStatusBody },
    TContext
> => {
    const mutationOptions =
        getPatchAdminReportsByIdStatusMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
