/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    AdminUserDetailResponse,
    AdminUserListItem,
    AdminUserListResponse,
    ErrorResponse,
    GetAdminUsersParams,
    UpdateUserStatusBody,
    UserId,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns a keyset-paginated list of users for admin tooling. Supports a case-insensitive substring search across email, firstName, lastName.
 */
export const getGetAdminUsersUrl = (params: GetAdminUsersParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/admin/users?${stringifiedParams}`
        : `/admin/users`;
};

export const getAdminUsers = async (
    params: GetAdminUsersParams,
    options?: RequestInit
): Promise<AdminUserListResponse> => {
    return apiFetcher<AdminUserListResponse>(getGetAdminUsersUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminUsersQueryKey = (params?: GetAdminUsersParams) => {
    return [`/admin/users`, ...(params ? [params] : [])] as const;
};

export const getGetAdminUsersQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAdminUsersQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminUsers>>
    > = () => getAdminUsers(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUsers>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminUsersQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminUsers>>
>;
export type GetAdminUsersQueryError = ErrorResponse;

export function useGetAdminUsers<
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminUsers>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminUsers>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUsers<
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminUsers>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminUsers>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUsers<
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminUsers<
    TData = Awaited<ReturnType<typeof getAdminUsers>>,
    TError = ErrorResponse,
>(
    params: GetAdminUsersParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsers>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminUsersQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns full user detail plus the most recent status history entries (newest first, capped at 50). changedBy is null for system-triggered changes or when the actor admin no longer exists.
 */
export const getGetAdminUsersByIdUrl = (id: UserId) => {
    return `/admin/users/${id}`;
};

export const getAdminUsersById = async (
    id: UserId,
    options?: RequestInit
): Promise<AdminUserDetailResponse> => {
    return apiFetcher<AdminUserDetailResponse>(getGetAdminUsersByIdUrl(id), {
        ...options,
        method: "GET",
    });
};

export const getGetAdminUsersByIdQueryKey = (id?: UserId) => {
    return [`/admin/users/${id}`] as const;
};

export const getGetAdminUsersByIdQueryOptions = <
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetAdminUsersByIdQueryKey(id);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getAdminUsersById>>
    > = () => getAdminUsersById(id, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getAdminUsersById>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetAdminUsersByIdQueryResult = NonNullable<
    Awaited<ReturnType<typeof getAdminUsersById>>
>;
export type GetAdminUsersByIdQueryError = ErrorResponse;

export function useGetAdminUsersById<
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminUsersById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminUsersById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUsersById<
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getAdminUsersById>>,
                    TError,
                    Awaited<ReturnType<typeof getAdminUsersById>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetAdminUsersById<
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetAdminUsersById<
    TData = Awaited<ReturnType<typeof getAdminUsersById>>,
    TError = ErrorResponse,
>(
    id: UserId,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getAdminUsersById>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetAdminUsersByIdQueryOptions(id, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Changes a user's account status (ACTIVE / SUSPENDED / BANNED / DELETED) and records an audit row in user_status_history. Admins cannot change their own status.
 */
export const getPatchAdminUsersByIdStatusUrl = (id: UserId) => {
    return `/admin/users/${id}/status`;
};

export const patchAdminUsersByIdStatus = async (
    id: UserId,
    updateUserStatusBody: UpdateUserStatusBody,
    options?: RequestInit
): Promise<AdminUserListItem> => {
    return apiFetcher<AdminUserListItem>(getPatchAdminUsersByIdStatusUrl(id), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(updateUserStatusBody),
    });
};

export const getPatchAdminUsersByIdStatusMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
        TError,
        { id: UserId; data: UpdateUserStatusBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
    TError,
    { id: UserId; data: UpdateUserStatusBody },
    TContext
> => {
    const mutationKey = ["patchAdminUsersByIdStatus"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
        { id: UserId; data: UpdateUserStatusBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchAdminUsersByIdStatus(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchAdminUsersByIdStatusMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>
>;
export type PatchAdminUsersByIdStatusMutationBody = UpdateUserStatusBody;
export type PatchAdminUsersByIdStatusMutationError = ErrorResponse;

export const usePatchAdminUsersByIdStatus = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
            TError,
            { id: UserId; data: UpdateUserStatusBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchAdminUsersByIdStatus>>,
    TError,
    { id: UserId; data: UpdateUserStatusBody },
    TContext
> => {
    const mutationOptions =
        getPatchAdminUsersByIdStatusMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
