/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    Car,
    CarBrandNameList,
    CarId,
    CarListItemList,
    CarModelList,
    CountryCodeResponseList,
    CreateCarBody,
    DeleteCarResponse,
    ErrorResponse,
    UpdateCarStatusBody,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns all available European country codes
 */
export const getGetCarsCountryCodesUrl = () => {
    return `/cars/country-codes`;
};

export const getCarsCountryCodes = async (
    options?: RequestInit
): Promise<CountryCodeResponseList> => {
    return apiFetcher<CountryCodeResponseList>(getGetCarsCountryCodesUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetCarsCountryCodesQueryKey = () => {
    return [`/cars/country-codes`] as const;
};

export const getGetCarsCountryCodesQueryOptions = <
    TData = Awaited<ReturnType<typeof getCarsCountryCodes>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getCarsCountryCodes>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCarsCountryCodesQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getCarsCountryCodes>>
    > = () => getCarsCountryCodes(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getCarsCountryCodes>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarsCountryCodesQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCarsCountryCodes>>
>;
export type GetCarsCountryCodesQueryError = ErrorResponse;

export function useGetCarsCountryCodes<
    TData = Awaited<ReturnType<typeof getCarsCountryCodes>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsCountryCodes>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCarsCountryCodes>>,
                    TError,
                    Awaited<ReturnType<typeof getCarsCountryCodes>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarsCountryCodes<
    TData = Awaited<ReturnType<typeof getCarsCountryCodes>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsCountryCodes>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCarsCountryCodes>>,
                    TError,
                    Awaited<ReturnType<typeof getCarsCountryCodes>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarsCountryCodes<
    TData = Awaited<ReturnType<typeof getCarsCountryCodes>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsCountryCodes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarsCountryCodes<
    TData = Awaited<ReturnType<typeof getCarsCountryCodes>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsCountryCodes>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCarsCountryCodesQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns all available car brands
 */
export const getGetCarsBrandsUrl = () => {
    return `/cars/brands`;
};

export const getCarsBrands = async (
    options?: RequestInit
): Promise<CarBrandNameList> => {
    return apiFetcher<CarBrandNameList>(getGetCarsBrandsUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetCarsBrandsQueryKey = () => {
    return [`/cars/brands`] as const;
};

export const getGetCarsBrandsQueryOptions = <
    TData = Awaited<ReturnType<typeof getCarsBrands>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getCarsBrands>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCarsBrandsQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getCarsBrands>>
    > = () => getCarsBrands(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getCarsBrands>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarsBrandsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCarsBrands>>
>;
export type GetCarsBrandsQueryError = ErrorResponse;

export function useGetCarsBrands<
    TData = Awaited<ReturnType<typeof getCarsBrands>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrands>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCarsBrands>>,
                    TError,
                    Awaited<ReturnType<typeof getCarsBrands>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarsBrands<
    TData = Awaited<ReturnType<typeof getCarsBrands>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrands>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCarsBrands>>,
                    TError,
                    Awaited<ReturnType<typeof getCarsBrands>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarsBrands<
    TData = Awaited<ReturnType<typeof getCarsBrands>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrands>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarsBrands<
    TData = Awaited<ReturnType<typeof getCarsBrands>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrands>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCarsBrandsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns car models for a given brand
 */
export const getGetCarsBrandsByBrandModelsUrl = (brand: string) => {
    return `/cars/brands/${brand}/models`;
};

export const getCarsBrandsByBrandModels = async (
    brand: string,
    options?: RequestInit
): Promise<CarModelList> => {
    return apiFetcher<CarModelList>(getGetCarsBrandsByBrandModelsUrl(brand), {
        ...options,
        method: "GET",
    });
};

export const getGetCarsBrandsByBrandModelsQueryKey = (brand?: string) => {
    return [`/cars/brands/${brand}/models`] as const;
};

export const getGetCarsBrandsByBrandModelsQueryOptions = <
    TData = Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
    TError = ErrorResponse,
>(
    brand: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetCarsBrandsByBrandModelsQueryKey(brand);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>
    > = () => getCarsBrandsByBrandModels(brand, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!brand,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarsBrandsByBrandModelsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>
>;
export type GetCarsBrandsByBrandModelsQueryError = ErrorResponse;

export function useGetCarsBrandsByBrandModels<
    TData = Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
    TError = ErrorResponse,
>(
    brand: string,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
                    TError,
                    Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarsBrandsByBrandModels<
    TData = Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
    TError = ErrorResponse,
>(
    brand: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
                    TError,
                    Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarsBrandsByBrandModels<
    TData = Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
    TError = ErrorResponse,
>(
    brand: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarsBrandsByBrandModels<
    TData = Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
    TError = ErrorResponse,
>(
    brand: string,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsBrandsByBrandModels>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCarsBrandsByBrandModelsQueryOptions(
        brand,
        options
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns the current user's cars
 */
export const getGetCarsMeUrl = () => {
    return `/cars/me`;
};

export const getCarsMe = async (
    options?: RequestInit
): Promise<CarListItemList> => {
    return apiFetcher<CarListItemList>(getGetCarsMeUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetCarsMeQueryKey = () => {
    return [`/cars/me`] as const;
};

export const getGetCarsMeQueryOptions = <
    TData = Awaited<ReturnType<typeof getCarsMe>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getCarsMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCarsMeQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCarsMe>>> = () =>
        getCarsMe(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getCarsMe>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCarsMeQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCarsMe>>
>;
export type GetCarsMeQueryError = ErrorResponse;

export function useGetCarsMe<
    TData = Awaited<ReturnType<typeof getCarsMe>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsMe>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCarsMe>>,
                    TError,
                    Awaited<ReturnType<typeof getCarsMe>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarsMe<
    TData = Awaited<ReturnType<typeof getCarsMe>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsMe>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCarsMe>>,
                    TError,
                    Awaited<ReturnType<typeof getCarsMe>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCarsMe<
    TData = Awaited<ReturnType<typeof getCarsMe>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsMe>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCarsMe<
    TData = Awaited<ReturnType<typeof getCarsMe>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCarsMe>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCarsMeQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Creates a new car for the current user
 */
export const getPostCarsMeUrl = () => {
    return `/cars/me`;
};

export const postCarsMe = async (
    createCarBody: CreateCarBody,
    options?: RequestInit
): Promise<Car> => {
    return apiFetcher<Car>(getPostCarsMeUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createCarBody),
    });
};

export const getPostCarsMeMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postCarsMe>>,
        TError,
        { data: CreateCarBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postCarsMe>>,
    TError,
    { data: CreateCarBody },
    TContext
> => {
    const mutationKey = ["postCarsMe"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postCarsMe>>,
        { data: CreateCarBody }
    > = (props) => {
        const { data } = props ?? {};

        return postCarsMe(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostCarsMeMutationResult = NonNullable<
    Awaited<ReturnType<typeof postCarsMe>>
>;
export type PostCarsMeMutationBody = CreateCarBody;
export type PostCarsMeMutationError = ErrorResponse;

export const usePostCarsMe = <TError = ErrorResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof postCarsMe>>,
            TError,
            { data: CreateCarBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof postCarsMe>>,
    TError,
    { data: CreateCarBody },
    TContext
> => {
    const mutationOptions = getPostCarsMeMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Updates whether the current user's car is active
 */
export const getPatchCarsByIdStatusUrl = (id: CarId) => {
    return `/cars/${id}/status`;
};

export const patchCarsByIdStatus = async (
    id: CarId,
    updateCarStatusBody: UpdateCarStatusBody,
    options?: RequestInit
): Promise<Car> => {
    return apiFetcher<Car>(getPatchCarsByIdStatusUrl(id), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(updateCarStatusBody),
    });
};

export const getPatchCarsByIdStatusMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchCarsByIdStatus>>,
        TError,
        { id: CarId; data: UpdateCarStatusBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchCarsByIdStatus>>,
    TError,
    { id: CarId; data: UpdateCarStatusBody },
    TContext
> => {
    const mutationKey = ["patchCarsByIdStatus"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchCarsByIdStatus>>,
        { id: CarId; data: UpdateCarStatusBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return patchCarsByIdStatus(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchCarsByIdStatusMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchCarsByIdStatus>>
>;
export type PatchCarsByIdStatusMutationBody = UpdateCarStatusBody;
export type PatchCarsByIdStatusMutationError = ErrorResponse;

export const usePatchCarsByIdStatus = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchCarsByIdStatus>>,
            TError,
            { id: CarId; data: UpdateCarStatusBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchCarsByIdStatus>>,
    TError,
    { id: CarId; data: UpdateCarStatusBody },
    TContext
> => {
    const mutationOptions = getPatchCarsByIdStatusMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Soft-deletes the current user's car. Rejects with CAR_IN_USE if the car has an active (PLANNED/IN_PROGRESS) ride.
 */
export const getDeleteCarsByIdUrl = (id: CarId) => {
    return `/cars/${id}`;
};

export const deleteCarsById = async (
    id: CarId,
    options?: RequestInit
): Promise<DeleteCarResponse> => {
    return apiFetcher<DeleteCarResponse>(getDeleteCarsByIdUrl(id), {
        ...options,
        method: "DELETE",
    });
};

export const getDeleteCarsByIdMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteCarsById>>,
        TError,
        { id: CarId },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteCarsById>>,
    TError,
    { id: CarId },
    TContext
> => {
    const mutationKey = ["deleteCarsById"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteCarsById>>,
        { id: CarId }
    > = (props) => {
        const { id } = props ?? {};

        return deleteCarsById(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteCarsByIdMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteCarsById>>
>;

export type DeleteCarsByIdMutationError = ErrorResponse;

export const useDeleteCarsById = <TError = ErrorResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteCarsById>>,
            TError,
            { id: CarId },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof deleteCarsById>>,
    TError,
    { id: CarId },
    TContext
> => {
    const mutationOptions = getDeleteCarsByIdMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
