/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { ReportId } from "./reportId";
import type { ReportType } from "./reportType";
import type { ReportStatus } from "./reportStatus";
import type { AdminReportDetailRideId } from "./adminReportDetailRideId";
import type { AdminReportDetailReporter } from "./adminReportDetailReporter";
import type { AdminReportDetailTarget } from "./adminReportDetailTarget";
import type { AdminReportDetailRide } from "./adminReportDetailRide";

export interface AdminReportDetail {
    id: ReportId;
    reportType: ReportType;
    reportStatus: ReportStatus;
    description: string;
    /** @nullable */
    rideId: AdminReportDetailRideId;
    reporter: AdminReportDetailReporter;
    target: AdminReportDetailTarget;
    createdAt: string;
    updatedAt: string;
    /** @nullable */
    resolutionReason: string | null;
    /** @nullable */
    ride: AdminReportDetailRide;
}
