/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { AdminUserListItem } from "./adminUserListItem";
import type { AdminUserListResponseNextCursor } from "./adminUserListResponseNextCursor";

export interface AdminUserListResponse {
    items: AdminUserListItem[];
    /** @nullable */
    nextCursor: AdminUserListResponseNextCursor;
}
