/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewId } from "./reviewId";
import type { RideId } from "./rideId";
import type { ReviewStatus } from "./reviewStatus";
import type { AdminReviewDetailAuthorRole } from "./adminReviewDetailAuthorRole";
import type { AdminReviewDetailSubjectRole } from "./adminReviewDetailSubjectRole";
import type { AdminReviewDetailAuthor } from "./adminReviewDetailAuthor";
import type { AdminReviewDetailSubject } from "./adminReviewDetailSubject";
import type { AdminReviewDetailRide } from "./adminReviewDetailRide";

export interface AdminReviewDetail {
    id: ReviewId;
    rideId: RideId;
    /**
     * @minimum 1
     * @maximum 5
     */
    rating: number;
    /** @nullable */
    comment: string | null;
    reviewStatus: ReviewStatus;
    authorRole: AdminReviewDetailAuthorRole;
    subjectRole: AdminReviewDetailSubjectRole;
    author: AdminReviewDetailAuthor;
    subject: AdminReviewDetailSubject;
    ride: AdminReviewDetailRide;
    createdAt: string;
    updatedAt: string;
}
