/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { UserRole } from "./userRole";
import type { UserStatus } from "./userStatus";

export interface AdminUserDetail {
    id: UserId;
    /**
     * @maxLength 254
     * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
     */
    email: string;
    /**
     * @minLength 1
     * @maxLength 20
     * @nullable
     */
    firstName: string | null;
    /**
     * @minLength 1
     * @maxLength 20
     * @nullable
     */
    lastName: string | null;
    /**
     * @minLength 1
     * @maxLength 20
     * @nullable
     * @pattern ^\S+$
     */
    displayName: string | null;
    /**
     * @maxLength 16
     * @nullable
     * @pattern ^\+[1-9]\d{1,14}$
     */
    phone: string | null;
    /**
     * @maxLength 500
     * @nullable
     */
    bio: string | null;
    /** @nullable */
    profilePhotoUrl: string | null;
    userRole: UserRole;
    userStatus: UserStatus;
    /** @nullable */
    emailVerifiedAt: string | null;
    /** @nullable */
    phoneVerifiedAt: string | null;
    /** @nullable */
    lastActiveAt: string | null;
    createdAt: string;
    updatedAt: string;
}
