/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { AdminUserDetail } from "./adminUserDetail";
import type { AdminUserStatusHistoryItem } from "./adminUserStatusHistoryItem";

export interface AdminUserDetailResponse {
    user: AdminUserDetail;
    statusHistory: AdminUserStatusHistoryItem[];
}
