/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type AdminRideDetailBookingsItemBookingStatus =
    (typeof AdminRideDetailBookingsItemBookingStatus)[keyof typeof AdminRideDetailBookingsItemBookingStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminRideDetailBookingsItemBookingStatus = {
    PENDING: "PENDING",
    CONFIRMED: "CONFIRMED",
    REJECTED: "REJECTED",
    CANCELLED: "CANCELLED",
    COMPLETED: "COMPLETED",
    NO_SHOW: "NO_SHOW",
} as const;
