/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { UserRole } from "./userRole";

export interface AdminUserListQuery {
    /**
     * @minimum 1
     * @maximum 100
     */
    limit: number;
    cursor?: UserId;
    role?: UserRole;
    /**
     * @minLength 1
     * @maxLength 100
     */
    search?: string;
}
