/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { AdminRideListItem } from "./adminRideListItem";
import type { AdminRideListResponseNextCursor } from "./adminRideListResponseNextCursor";

export interface AdminRideListResponse {
    items: AdminRideListItem[];
    /** @nullable */
    nextCursor: AdminRideListResponseNextCursor;
}
