/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type AdminSettableUserStatus =
    (typeof AdminSettableUserStatus)[keyof typeof AdminSettableUserStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const AdminSettableUserStatus = {
    ACTIVE: "ACTIVE",
    SUSPENDED: "SUSPENDED",
    BANNED: "BANNED",
} as const;
