/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export interface AdminDashboardUserMetrics {
    /**
     * @minimum 0
     * @maximum 9007199254740991
     */
    totalRegistered: number;
    /**
     * @minimum 0
     * @maximum 9007199254740991
     */
    activeInLast24h: number;
    /**
     * @minimum 0
     * @maximum 9007199254740991
     */
    drivers: number;
    /**
     * @minimum 0
     * @maximum 9007199254740991
     */
    passengers: number;
    /**
     * @minimum 0
     * @maximum 9007199254740991
     */
    pendingVerification: number;
    /**
     * @minimum 0
     * @maximum 9007199254740991
     */
    bannedAccounts: number;
}
