/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { RideStatus } from "./rideStatus";

export interface AdminRideListQuery {
    /**
     * @minimum 1
     * @maximum 100
     */
    limit: number;
    cursor?: RideId;
    status?: RideStatus;
    /**
     * @minLength 1
     * @maxLength 100
     */
    search?: string;
}
