/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { RideStatus } from "./rideStatus";
import type { Currency } from "./currency";
import type { AdminRideDetailDriver } from "./adminRideDetailDriver";
import type { AdminRideDetailCar } from "./adminRideDetailCar";
import type { AdminRideDetailStopsItem } from "./adminRideDetailStopsItem";
import type { AdminRideDetailPricesItem } from "./adminRideDetailPricesItem";
import type { AdminRideDetailBookingsItem } from "./adminRideDetailBookingsItem";

export interface AdminRideDetail {
    id: RideId;
    rideStatus: RideStatus;
    departureAt: string;
    /** @nullable */
    arrivalEstimateAt: string | null;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    offeredSeats: number;
    currency: Currency;
    /** @nullable */
    description: string | null;
    createdAt: string;
    updatedAt: string;
    driver: AdminRideDetailDriver;
    car: AdminRideDetailCar;
    stops: AdminRideDetailStopsItem[];
    prices: AdminRideDetailPricesItem[];
    bookings: AdminRideDetailBookingsItem[];
}
