/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { AuthoredReviewListItemSubjectFirstName } from "./authoredReviewListItemSubjectFirstName";
import type { AuthoredReviewListItemSubjectLastName } from "./authoredReviewListItemSubjectLastName";
import type { AuthoredReviewListItemSubjectProfilePhotoUrl } from "./authoredReviewListItemSubjectProfilePhotoUrl";

export type AuthoredReviewListItemSubject = {
    id: UserId;
    firstName: AuthoredReviewListItemSubjectFirstName;
    lastName: AuthoredReviewListItemSubjectLastName;
    profilePhotoUrl: AuthoredReviewListItemSubjectProfilePhotoUrl;
};
