/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { AvailableRideItemDriverFirstName } from "./availableRideItemDriverFirstName";
import type { AvailableRideItemDriverLastName } from "./availableRideItemDriverLastName";
import type { AvailableRideItemDriverProfilePhotoUrl } from "./availableRideItemDriverProfilePhotoUrl";
import type { AvailableRideItemDriverAverageRating } from "./availableRideItemDriverAverageRating";

export type AvailableRideItemDriver = {
    id: UserId;
    firstName: AvailableRideItemDriverFirstName;
    lastName: AvailableRideItemDriverLastName;
    profilePhotoUrl: AvailableRideItemDriverProfilePhotoUrl;
    averageRating: AvailableRideItemDriverAverageRating;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    reviewCount: number;
};
