/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideStopId } from "./rideStopId";

export type AvailableRideItemPickupStop = {
    pickupStopId: RideStopId;
    city: string;
    /** @nullable */
    plannedDepartureAt: string | null;
};
