/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type BlockReason = (typeof BlockReason)[keyof typeof BlockReason];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const BlockReason = {
    HARASSMENT: "HARASSMENT",
    SPAM: "SPAM",
    SAFETY: "SAFETY",
    FRAUD: "FRAUD",
    ABUSE: "ABUSE",
    OTHER: "OTHER",
} as const;
