/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { CarId } from "./carId";
import type { UserId } from "./userId";
import type { CarModelId } from "./carModelId";
import type { CountryCode } from "./countryCode";
import type { CarColor } from "./carColor";

export interface Car {
    id: CarId;
    ownerId: UserId;
    modelId: CarModelId;
    /**
     * @minLength 2
     * @maxLength 12
     * @pattern ^[A-Z0-9]+$
     */
    spz: string;
    countryCode: CountryCode;
    /** @nullable */
    color: CarColor;
    /**
     * @minimum 0
     * @maximum 9007199254740991
     * @exclusiveMinimum
     */
    seatsTotal: number;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
    /** @nullable */
    deletedAt: string | null;
}
