/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

/**
 * @nullable
 */
export type CarColor = (typeof CarColor)[keyof typeof CarColor] | null;

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CarColor = {
    WHITE: "WHITE",
    BLACK: "BLACK",
    SILVER: "SILVER",
    GRAY: "GRAY",
    RED: "RED",
    BLUE: "BLUE",
    BROWN: "BROWN",
    GREEN: "GREEN",
    YELLOW: "YELLOW",
    ORANGE: "ORANGE",
    OTHER: "OTHER",
} as const;
