/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { CarId } from "./carId";
import type { UserId } from "./userId";
import type { CarModelId } from "./carModelId";
import type { CountryCode } from "./countryCode";
import type { CarListItemColor } from "./carListItemColor";

export interface CarListItem {
    id: CarId;
    ownerId: UserId;
    modelId: CarModelId;
    /**
     * @minLength 1
     * @maxLength 100
     */
    brand: string;
    /**
     * @minLength 1
     * @maxLength 100
     */
    modelName: string;
    /**
     * @minLength 2
     * @maxLength 12
     * @pattern ^[A-Z0-9]+$
     */
    spz: string;
    countryCode: CountryCode;
    color: CarListItemColor;
    /**
     * @maximum 9007199254740991
     */
    seatsTotal: number;
    isActive: boolean;
    createdAt: string;
    updatedAt: string;
}
