/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

/**
 * @minimum 0
 * @maximum 9007199254740991
 * @exclusiveMinimum
 */
export type CarModelId = number;
