/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { CarModelId } from "./carModelId";

export interface CarModel {
    id: CarModelId;
    /**
     * @minLength 1
     * @maxLength 100
     */
    brand: string;
    /**
     * @minLength 1
     * @maxLength 100
     */
    modelName: string;
}
