/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { CityId } from "./cityId";
import type { CountryCode } from "./countryCode";

export interface CityListItem {
    id: CityId;
    /**
     * @minLength 1
     * @maxLength 200
     */
    name: string;
    countryCode: CountryCode;
    /**
     * @minimum -90
     * @maximum 90
     */
    lat: number;
    /**
     * @minimum -180
     * @maximum 180
     */
    lng: number;
    /**
     * @minimum 0
     * @maximum 9007199254740991
     */
    population: number;
}
