/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { Message } from "./message";

/**
 * @nullable
 */
export type ConversationListItemLastMessage = Message | null;
