/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type ConversationListItemConversationType =
    (typeof ConversationListItemConversationType)[keyof typeof ConversationListItemConversationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ConversationListItemConversationType = {
    RIDE: "RIDE",
    BOOKING: "BOOKING",
    SUPPORT: "SUPPORT",
} as const;
