/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { ConversationListItemConversationType } from "./conversationListItemConversationType";
import type { ConversationRole } from "./conversationRole";
import type { PublicUserPreview } from "./publicUserPreview";
import type { ConversationListItemLastMessage } from "./conversationListItemLastMessage";

export interface ConversationListItem {
    /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
    id: string;
    conversationType: ConversationListItemConversationType;
    /**
     * @nullable
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    bookingId: string | null;
    /**
     * @nullable
     * @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$
     */
    rideId: string | null;
    myRole: ConversationRole;
    counterpart: PublicUserPreview;
    /** @nullable */
    lastMessage: ConversationListItemLastMessage;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    unreadCount: number;
    updatedAt: string;
    isBlocked: boolean;
}
