/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type CountryCode = (typeof CountryCode)[keyof typeof CountryCode];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const CountryCode = {
    AT: "AT",
    BE: "BE",
    BG: "BG",
    HR: "HR",
    CY: "CY",
    CZ: "CZ",
    DK: "DK",
    EE: "EE",
    FI: "FI",
    FR: "FR",
    DE: "DE",
    GR: "GR",
    HU: "HU",
    IE: "IE",
    IT: "IT",
    LV: "LV",
    LT: "LT",
    LU: "LU",
    MT: "MT",
    NL: "NL",
    PL: "PL",
    PT: "PT",
    RO: "RO",
    SK: "SK",
    SI: "SI",
    ES: "ES",
    SE: "SE",
    IS: "IS",
    LI: "LI",
    NO: "NO",
    CH: "CH",
} as const;
