/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { CreateBookingBodyPickupStopId } from "./createBookingBodyPickupStopId";
import type { CreateBookingBodyDropoffStopId } from "./createBookingBodyDropoffStopId";
import type { CreateBookingBodyDynamicPickup } from "./createBookingBodyDynamicPickup";
import type { CreateBookingBodyDynamicDropoff } from "./createBookingBodyDynamicDropoff";

export interface CreateBookingBody {
    rideId: RideId;
    pickupStopId: CreateBookingBodyPickupStopId;
    dropoffStopId: CreateBookingBodyDropoffStopId;
    /**
     * @minimum 1
     * @maximum 9007199254740991
     */
    seatCount: number;
    dynamicPickup?: CreateBookingBodyDynamicPickup;
    dynamicDropoff?: CreateBookingBodyDynamicDropoff;
    priceAmount?: number;
    requestedPickupCity?: string;
    requestedDropoffCity?: string;
}
