/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { CarId } from "./carId";
import type { CreateRideBodyArrivalEstimateAt } from "./createRideBodyArrivalEstimateAt";
import type { Currency } from "./currency";
import type { CreateRideBodyDescription } from "./createRideBodyDescription";
import type { CreateRideBodyStopsItem } from "./createRideBodyStopsItem";
import type { CreateRideBodyPricesItem } from "./createRideBodyPricesItem";

export interface CreateRideBody {
    carId: CarId;
    departureAt: string;
    arrivalEstimateAt?: CreateRideBodyArrivalEstimateAt;
    /**
     * @minimum 1
     * @maximum 9007199254740991
     */
    offeredSeats: number;
    currency: Currency;
    description?: CreateRideBodyDescription;
    /** @minItems 2 */
    stops: CreateRideBodyStopsItem[];
    prices?: CreateRideBodyPricesItem[];
}
