/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { CarModelId } from "./carModelId";
import type { CountryCode } from "./countryCode";
import type { CreateCarBodyColor } from "./createCarBodyColor";

export interface CreateCarBody {
    modelId: CarModelId;
    /**
     * @minLength 2
     * @maxLength 12
     * @pattern ^[A-Z0-9]+$
     */
    spz: string;
    countryCode: CountryCode;
    color: CreateCarBodyColor;
    /**
     * @minimum 2
     * @maximum 9
     */
    seatsTotal: number;
}
