/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { RideId } from "./rideId";
import type { ReportType } from "./reportType";

export interface CreateReportBody {
    targetUserId: UserId;
    rideId?: RideId;
    reportType: ReportType;
    /**
     * @minLength 1
     * @maxLength 2000
     */
    description: string;
    blockTarget?: boolean;
}
