/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { RideStopId } from "./rideStopId";

export interface CreateBookingBody {
    rideId: RideId;
    pickupStopId: RideStopId;
    dropoffStopId: RideStopId;
    /**
     * @minimum 1
     * @maximum 9007199254740991
     */
    seatCount: number;
}
