/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { UserId } from "./userId";

export interface CreateReviewBody {
    rideId: RideId;
    subjectId: UserId;
    /**
     * @minimum 1
     * @maximum 5
     */
    rating: number;
    /** @maxLength 1000 */
    comment?: string;
}
