/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { CityId } from "./cityId";

export type CreateRideBodyStopsItem = {
    cityId: CityId;
    /**
     * @minLength 1
     * @maxLength 255
     */
    address: string;
    /**
     * @minimum -90
     * @maximum 90
     */
    lat: number;
    /**
     * @minimum -180
     * @maximum 180
     */
    lng: number;
    /** @nullable */
    plannedArrivalAt?: string | null;
    /** @nullable */
    plannedDepartureAt?: string | null;
};
