/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { DriverRideRequestItemPassengerFirstName } from "./driverRideRequestItemPassengerFirstName";
import type { DriverRideRequestItemPassengerLastName } from "./driverRideRequestItemPassengerLastName";
import type { DriverRideRequestItemPassengerProfilePhotoUrl } from "./driverRideRequestItemPassengerProfilePhotoUrl";
import type { DriverRideRequestItemPassengerAverageRating } from "./driverRideRequestItemPassengerAverageRating";

export type DriverRideRequestItemPassenger = {
    id: UserId;
    firstName: DriverRideRequestItemPassengerFirstName;
    lastName: DriverRideRequestItemPassengerLastName;
    profilePhotoUrl: DriverRideRequestItemPassengerProfilePhotoUrl;
    averageRating: DriverRideRequestItemPassengerAverageRating;
};
