/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { Currency } from "./currency";
import type { DriverRideRequestItemPassenger } from "./driverRideRequestItemPassenger";

export interface DriverRideRequestItem {
    /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
    id: string;
    rideId: RideId;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    seatCount: number;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    priceAmount: number;
    currency: Currency;
    passenger: DriverRideRequestItemPassenger;
    pickupCity: string;
    dropoffCity: string;
    /** @nullable */
    requestedPickupCity: string | null;
    /** @nullable */
    requestedDropoffCity: string | null;
    originalStartCity: string;
    originalEndCity: string;
    departureAt: string;
}
