/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type GetRidesSearchParams = {
    /**
     * @minimum -90
     * @maximum 90
     */
    startLat: number;
    /**
     * @minimum -180
     * @maximum 180
     */
    startLng: number;
    startCity?: string;
    /**
     * @minimum -90
     * @maximum 90
     */
    destLat: number;
    /**
     * @minimum -180
     * @maximum 180
     */
    destLng: number;
    destCity?: string;
    travelDate: string;
};
