/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewId } from "./reviewId";
import type { ReviewStatus } from "./reviewStatus";
import type { GetReviewsAdminSubjectRole } from "./getReviewsAdminSubjectRole";

export type GetReviewsAdminParams = {
    /**
     * @minimum 1
     * @maximum 100
     */
    limit?: number;
    cursor?: ReviewId;
    status?: ReviewStatus;
    /**
     * @minimum 1
     * @maximum 5
     */
    minRating?: number;
    /**
     * @minimum 1
     * @maximum 5
     */
    maxRating?: number;
    subjectRole?: GetReviewsAdminSubjectRole;
    /**
     * @minLength 1
     * @maxLength 100
     */
    search?: string;
};
