/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type MessageMessageType =
    (typeof MessageMessageType)[keyof typeof MessageMessageType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const MessageMessageType = {
    TEXT: "TEXT",
    SYSTEM: "SYSTEM",
} as const;
