/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type NotificationNotificationType =
    (typeof NotificationNotificationType)[keyof typeof NotificationNotificationType];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const NotificationNotificationType = {
    BOOKING_REQUEST: "BOOKING_REQUEST",
    BOOKING_CONFIRMED: "BOOKING_CONFIRMED",
    BOOKING_CANCELLED: "BOOKING_CANCELLED",
    MESSAGE_RECEIVED: "MESSAGE_RECEIVED",
    RIDE_UPDATED: "RIDE_UPDATED",
    REVIEW_RECEIVED: "REVIEW_RECEIVED",
    BOOKING_REJECTED: "BOOKING_REJECTED",
    RIDE_CANCELLED: "RIDE_CANCELLED",
    RIDE_COMPLETED: "RIDE_COMPLETED",
} as const;
