/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { PassengerBookingListItemDriverFirstName } from "./passengerBookingListItemDriverFirstName";
import type { PassengerBookingListItemDriverLastName } from "./passengerBookingListItemDriverLastName";
import type { PassengerBookingListItemDriverProfilePhotoUrl } from "./passengerBookingListItemDriverProfilePhotoUrl";
import type { PassengerBookingListItemDriverAverageRating } from "./passengerBookingListItemDriverAverageRating";

export type PassengerBookingListItemDriver = {
    id: UserId;
    firstName: PassengerBookingListItemDriverFirstName;
    lastName: PassengerBookingListItemDriverLastName;
    profilePhotoUrl: PassengerBookingListItemDriverProfilePhotoUrl;
    averageRating: PassengerBookingListItemDriverAverageRating;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    reviewCount: number;
};
