/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { PassengerBookingListItemBookingStatus } from "./passengerBookingListItemBookingStatus";
import type { Currency } from "./currency";
import type { PassengerBookingListItemRide } from "./passengerBookingListItemRide";
import type { PublicUserPreviewWithRating } from "./publicUserPreviewWithRating";
import type { PassengerBookingListItemMyReviewOfDriver } from "./passengerBookingListItemMyReviewOfDriver";

export interface PassengerBookingListItem {
    /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
    id: string;
    bookingStatus: PassengerBookingListItemBookingStatus;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    priceAmount: number;
    currency: Currency;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    seatsLeft: number;
    ride: PassengerBookingListItemRide;
    driver: PublicUserPreviewWithRating;
    pickupCity: string;
    dropoffCity: string;
    /** @nullable */
    requestedPickupCity: string | null;
    /** @nullable */
    requestedDropoffCity: string | null;
    originalStartCity: string;
    originalEndCity: string;
    /** @nullable */
    myReviewOfDriver: PassengerBookingListItemMyReviewOfDriver;
}
