/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { PassengerBookingDetailBookingStatus } from "./passengerBookingDetailBookingStatus";
import type { Currency } from "./currency";
import type { PassengerBookingDetailRide } from "./passengerBookingDetailRide";
import type { PublicUserPreviewWithRating } from "./publicUserPreviewWithRating";
import type { PassengerBookingDetailCar } from "./passengerBookingDetailCar";
import type { PublicUserPreview } from "./publicUserPreview";

export interface PassengerBookingDetail {
    /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
    id: string;
    bookingStatus: PassengerBookingDetailBookingStatus;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    priceAmount: number;
    currency: Currency;
    ride: PassengerBookingDetailRide;
    driver: PublicUserPreviewWithRating;
    car: PassengerBookingDetailCar;
    pickupCity: string;
    dropoffCity: string;
    /** @nullable */
    requestedPickupCity: string | null;
    /** @nullable */
    requestedDropoffCity: string | null;
    originalStartCity: string;
    originalEndCity: string;
    coPassengers: PublicUserPreview[];
}
