/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";

export interface PublicUserPreviewWithRating {
    id: UserId;
    /** @nullable */
    firstName: string | null;
    /** @nullable */
    lastName: string | null;
    /** @nullable */
    profilePhotoUrl: string | null;
    /** @nullable */
    averageRating: number | null;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    reviewCount: number;
}
