/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { PublicDriverProfileFirstName } from "./publicDriverProfileFirstName";
import type { PublicDriverProfileLastName } from "./publicDriverProfileLastName";
import type { PublicDriverProfileProfilePhotoUrl } from "./publicDriverProfileProfilePhotoUrl";

export interface PublicDriverProfile {
    id: UserId;
    firstName: PublicDriverProfileFirstName;
    lastName: PublicDriverProfileLastName;
    profilePhotoUrl: PublicDriverProfileProfilePhotoUrl;
}
