/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { ReviewId } from "./reviewId";
import type { RideId } from "./rideId";
import type { ReviewStatus } from "./reviewStatus";
import type { ReviewListItemAuthor } from "./reviewListItemAuthor";

export interface ReviewListItem {
    id: ReviewId;
    rideId: RideId;
    /**
     * @minimum 1
     * @maximum 5
     */
    rating: number;
    /**
     * @maxLength 1000
     * @nullable
     */
    comment: string | null;
    reviewStatus: ReviewStatus;
    createdAt: string;
    author: ReviewListItemAuthor;
}
