/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { ReviewListItemAuthorFirstName } from "./reviewListItemAuthorFirstName";
import type { ReviewListItemAuthorLastName } from "./reviewListItemAuthorLastName";
import type { ReviewListItemAuthorProfilePhotoUrl } from "./reviewListItemAuthorProfilePhotoUrl";

export type ReviewListItemAuthor = {
    id: UserId;
    firstName: ReviewListItemAuthorFirstName;
    lastName: ReviewListItemAuthorLastName;
    profilePhotoUrl: ReviewListItemAuthorProfilePhotoUrl;
};
