/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type ReviewStatus = (typeof ReviewStatus)[keyof typeof ReviewStatus];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const ReviewStatus = {
    VISIBLE: "VISIBLE",
    HIDDEN: "HIDDEN",
    REMOVED: "REMOVED",
} as const;
