/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { Currency } from "./currency";
import type { RideStopId } from "./rideStopId";

export type RideListItemPricesItem = {
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    amount: number;
    currency: Currency;
    startStopId: RideStopId;
    endStopId: RideStopId;
};
