/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type RideEndSource = (typeof RideEndSource)[keyof typeof RideEndSource];

// eslint-disable-next-line @typescript-eslint/no-redeclare
export const RideEndSource = {
    DRIVER: "DRIVER",
    AUTO: "AUTO",
    ADMIN: "ADMIN",
} as const;
