/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { UserId } from "./userId";
import type { CarId } from "./carId";
import type { RideStatus } from "./rideStatus";
import type { RideListItemArrivalEstimateAt } from "./rideListItemArrivalEstimateAt";
import type { Currency } from "./currency";
import type { RideListItemDescription } from "./rideListItemDescription";
import type { RideListItemDeletedAt } from "./rideListItemDeletedAt";
import type { RideListItemRideStopsItem } from "./rideListItemRideStopsItem";
import type { RideListItemBookingsItem } from "./rideListItemBookingsItem";
import type { RideListItemPricesItem } from "./rideListItemPricesItem";

export interface RideListItem {
    id: RideId;
    driverId: UserId;
    carId: CarId;
    rideStatus: RideStatus;
    departureAt: string;
    arrivalEstimateAt: RideListItemArrivalEstimateAt;
    /**
     * @minimum 1
     * @maximum 9007199254740991
     */
    offeredSeats: number;
    currency: Currency;
    description: RideListItemDescription;
    createdAt: string;
    updatedAt: string;
    deletedAt: RideListItemDeletedAt;
    rideStops: RideListItemRideStopsItem[];
    bookings: RideListItemBookingsItem[];
    prices: RideListItemPricesItem[];
}
