/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { RideSearchResultItemDriverProfilePhotoUrl } from "./rideSearchResultItemDriverProfilePhotoUrl";
import type { RideSearchResultItemDriverAverageRating } from "./rideSearchResultItemDriverAverageRating";

export type RideSearchResultItemDriver = {
    id: UserId;
    firstName: string;
    lastName: string;
    profilePhotoUrl: RideSearchResultItemDriverProfilePhotoUrl;
    averageRating: RideSearchResultItemDriverAverageRating;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    reviewCount: number;
};
