/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RidePassengersViewPassengersItemBookingStatus } from "./ridePassengersViewPassengersItemBookingStatus";
import type { PublicUserPreviewWithRating } from "./publicUserPreviewWithRating";
import type { RidePassengersViewPassengersItemPickupStop } from "./ridePassengersViewPassengersItemPickupStop";
import type { RidePassengersViewPassengersItemDropoffStop } from "./ridePassengersViewPassengersItemDropoffStop";
import type { RidePassengersViewPassengersItemMyReviewOfPassenger } from "./ridePassengersViewPassengersItemMyReviewOfPassenger";

export type RidePassengersViewPassengersItem = {
    /** @pattern ^([0-9a-fA-F]{8}-[0-9a-fA-F]{4}-[1-8][0-9a-fA-F]{3}-[89abAB][0-9a-fA-F]{3}-[0-9a-fA-F]{12}|00000000-0000-0000-0000-000000000000|ffffffff-ffff-ffff-ffff-ffffffffffff)$ */
    bookingId: string;
    bookingStatus: RidePassengersViewPassengersItemBookingStatus;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    seatCount: number;
    passenger: PublicUserPreviewWithRating;
    /** @nullable */
    requestedPickupCity: string | null;
    /** @nullable */
    requestedDropoffCity: string | null;
    /** @nullable */
    pickupStop: RidePassengersViewPassengersItemPickupStop;
    /** @nullable */
    dropoffStop: RidePassengersViewPassengersItemDropoffStop;
    /** @nullable */
    myReviewOfPassenger: RidePassengersViewPassengersItemMyReviewOfPassenger;
};
