/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { RideStatus } from "./rideStatus";
import type { PublicUserPreviewWithRating } from "./publicUserPreviewWithRating";
import type { RideSearchResultItemPickupStop } from "./rideSearchResultItemPickupStop";
import type { RideSearchResultItemDropoffStop } from "./rideSearchResultItemDropoffStop";
import type { Currency } from "./currency";

export interface RideSearchResultItem {
    rideId: RideId;
    departureAt: string;
    rideStatus: RideStatus;
    offeredSeats: number;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    seatsLeft: number;
    driver: PublicUserPreviewWithRating;
    pickupStop: RideSearchResultItemPickupStop;
    dropoffStop: RideSearchResultItemDropoffStop;
    /** @nullable */
    priceAmount: number | null;
    currency: Currency;
}
