/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { UserId } from "./userId";
import type { CarId } from "./carId";
import type { RideStatus } from "./rideStatus";
import type { RideEndedByUserId } from "./rideEndedByUserId";
import type { RideEndSourceProperty } from "./rideEndSourceProperty";
import type { Currency } from "./currency";

export interface Ride {
    id: RideId;
    driverId: UserId;
    carId: CarId;
    rideStatus: RideStatus;
    departureAt: string;
    /** @nullable */
    arrivalEstimateAt: string | null;
    /** @nullable */
    autoEndAt: string | null;
    /** @nullable */
    endedAt: string | null;
    /** @nullable */
    endedByUserId: RideEndedByUserId;
    /** @nullable */
    endSource: RideEndSourceProperty;
    /**
     * @maxLength 500
     * @nullable
     */
    endReason: string | null;
    /** @nullable */
    autoEndProcessedAt: string | null;
    /**
     * @minimum 1
     * @maximum 9007199254740991
     */
    offeredSeats: number;
    currency: Currency;
    /**
     * @maxLength 500
     * @nullable
     */
    description: string | null;
    createdAt: string;
    updatedAt: string;
    /** @nullable */
    deletedAt: string | null;
}
