/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export type RideSearchResultItemPickupStop = {
    pickupStopId: string;
    isDynamic?: boolean;
    lat?: number;
    lng?: number;
    city: string;
    /** @nullable */
    plannedDepartureAt: string | null;
    distanceKm?: number;
};
