/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { UserId } from "./userId";
import type { CarId } from "./carId";
import type { RideStatus } from "./rideStatus";
import type { RideArrivalEstimateAt } from "./rideArrivalEstimateAt";
import type { Currency } from "./currency";
import type { RideDescription } from "./rideDescription";
import type { RideDeletedAt } from "./rideDeletedAt";

export interface Ride {
    id: RideId;
    driverId: UserId;
    carId: CarId;
    rideStatus: RideStatus;
    departureAt: string;
    arrivalEstimateAt: RideArrivalEstimateAt;
    /**
     * @minimum 1
     * @maximum 9007199254740991
     */
    offeredSeats: number;
    currency: Currency;
    description: RideDescription;
    createdAt: string;
    updatedAt: string;
    deletedAt: RideDeletedAt;
}
