/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { RideId } from "./rideId";
import type { RideStatus } from "./rideStatus";
import type { Currency } from "./currency";
import type { RidePassengersViewRideRideStopsItem } from "./ridePassengersViewRideRideStopsItem";

export type RidePassengersViewRide = {
    id: RideId;
    departureAt: string;
    rideStatus: RideStatus;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    offeredSeats: number;
    currency: Currency;
    rideStops: RidePassengersViewRideRideStopsItem[];
    canReview: boolean;
};
