/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export interface SendMessageBody {
    /**
     * @minLength 1
     * @maxLength 2000
     */
    content: string;
}
