/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */

export interface UpdateUserBody {
    /**
     * @minLength 1
     * @maxLength 20
     */
    firstName?: string;
    /**
     * @minLength 1
     * @maxLength 20
     */
    lastName?: string;
    /**
     * @minLength 1
     * @maxLength 20
     * @pattern ^\S+$
     */
    displayName?: string;
    /**
     * @maxLength 16
     * @pattern ^\+[1-9]\d{1,14}$
     */
    phone?: string;
    /** @maxLength 500 */
    bio?: string;
    profilePhotoUrl?: string;
}
