/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { ReviewListItemList } from "./reviewListItemList";

export interface UserReviewsView {
    subjectId: UserId;
    /** @nullable */
    averageRating: number | null;
    /**
     * @minimum -9007199254740991
     * @maximum 9007199254740991
     */
    reviewCount: number;
    reviews: ReviewListItemList;
}
