/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import type { UserId } from "./userId";
import type { UserImage } from "./userImage";
import type { UserFirstName } from "./userFirstName";
import type { UserLastName } from "./userLastName";
import type { UserDisplayName } from "./userDisplayName";
import type { UserPhone } from "./userPhone";
import type { UserProfilePhotoUrl } from "./userProfilePhotoUrl";
import type { UserBio } from "./userBio";
import type { UserStatus } from "./userStatus";
import type { UserEmailVerifiedAt } from "./userEmailVerifiedAt";
import type { UserPhoneVerifiedAt } from "./userPhoneVerifiedAt";
import type { UserLastActiveAt } from "./userLastActiveAt";
import type { UserDeletedAt } from "./userDeletedAt";

export interface User {
    id: UserId;
    name: string;
    /**
     * @maxLength 254
     * @pattern ^(?!\.)(?!.*\.\.)([A-Za-z0-9_'+\-\.]*)[A-Za-z0-9_+-]@([A-Za-z0-9][A-Za-z0-9\-]*\.)+[A-Za-z]{2,}$
     */
    email: string;
    emailVerified: boolean;
    image: UserImage;
    firstName: UserFirstName;
    lastName: UserLastName;
    displayName: UserDisplayName;
    phone: UserPhone;
    profilePhotoUrl: UserProfilePhotoUrl;
    bio: UserBio;
    userStatus: UserStatus;
    emailVerifiedAt: UserEmailVerifiedAt;
    phoneVerifiedAt: UserPhoneVerifiedAt;
    lastActiveAt: UserLastActiveAt;
    createdAt: string;
    updatedAt: string;
    deletedAt: UserDeletedAt;
}
