/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    CityListItemList,
    ErrorResponse,
    GetCitiesParams,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns cities matching the query prefix, ranked by population. Used by the ride creation and search forms to restrict stop selection to known cities.
 */
export const getGetCitiesUrl = (params: GetCitiesParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/cities/?${stringifiedParams}`
        : `/cities/`;
};

export const getCities = async (
    params: GetCitiesParams,
    options?: RequestInit
): Promise<CityListItemList> => {
    return apiFetcher<CityListItemList>(getGetCitiesUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetCitiesQueryKey = (params?: GetCitiesParams) => {
    return [`/cities/`, ...(params ? [params] : [])] as const;
};

export const getGetCitiesQueryOptions = <
    TData = Awaited<ReturnType<typeof getCities>>,
    TError = ErrorResponse,
>(
    params: GetCitiesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCities>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetCitiesQueryKey(params);

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getCities>>> = () =>
        getCities(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getCities>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetCitiesQueryResult = NonNullable<
    Awaited<ReturnType<typeof getCities>>
>;
export type GetCitiesQueryError = ErrorResponse;

export function useGetCities<
    TData = Awaited<ReturnType<typeof getCities>>,
    TError = ErrorResponse,
>(
    params: GetCitiesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCities>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCities>>,
                    TError,
                    Awaited<ReturnType<typeof getCities>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCities<
    TData = Awaited<ReturnType<typeof getCities>>,
    TError = ErrorResponse,
>(
    params: GetCitiesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCities>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getCities>>,
                    TError,
                    Awaited<ReturnType<typeof getCities>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetCities<
    TData = Awaited<ReturnType<typeof getCities>>,
    TError = ErrorResponse,
>(
    params: GetCitiesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCities>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetCities<
    TData = Awaited<ReturnType<typeof getCities>>,
    TError = ErrorResponse,
>(
    params: GetCitiesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getCities>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetCitiesQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}
