/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as PassengerRouteRouteImport } from './routes/passenger/route'
import { Route as ForgotPasswordRouteRouteImport } from './routes/forgot-password/route'
import { Route as DriverRouteRouteImport } from './routes/driver/route'
import { Route as AdminRouteRouteImport } from './routes/admin/route'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassengerIndexRouteImport } from './routes/passenger/index'
import { Route as ForgotPasswordIndexRouteImport } from './routes/forgot-password/index'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PassengerRidesIndexRouteImport } from './routes/passenger/rides/index'
import { Route as PassengerRatingsIndexRouteImport } from './routes/passenger/ratings/index'
import { Route as PassengerProfileIndexRouteImport } from './routes/passenger/profile/index'
import { Route as PassengerChatIndexRouteImport } from './routes/passenger/chat/index'
import { Route as DriverRidesIndexRouteImport } from './routes/driver/rides/index'
import { Route as DriverRequestsIndexRouteImport } from './routes/driver/requests/index'
import { Route as DriverRatingsIndexRouteImport } from './routes/driver/ratings/index'
import { Route as DriverProfileIndexRouteImport } from './routes/driver/profile/index'
import { Route as DriverOfferIndexRouteImport } from './routes/driver/offer/index'
import { Route as DriverChatIndexRouteImport } from './routes/driver/chat/index'
import { Route as CarAddIndexRouteImport } from './routes/car/add/index'
import { Route as AdminUsersIndexRouteImport } from './routes/admin/users/index'
import { Route as AdminRidesIndexRouteImport } from './routes/admin/rides/index'
import { Route as AdminReviewsIndexRouteImport } from './routes/admin/reviews/index'
import { Route as AdminReportsIndexRouteImport } from './routes/admin/reports/index'
import { Route as PassengerRidesSearchIndexRouteImport } from './routes/passenger/rides/search/index'
import { Route as DriverRidesRateIndexRouteImport } from './routes/driver/rides/rate/index'
import { Route as DriverRidesPassengersIndexRouteImport } from './routes/driver/rides/passengers/index'

const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRouteRoute = PassengerRouteRouteImport.update({
  id: '/passenger',
  path: '/passenger',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRouteRoute = ForgotPasswordRouteRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRouteRoute = DriverRouteRouteImport.update({
  id: '/driver',
  path: '/driver',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRouteRoute = AdminRouteRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerIndexRoute = PassengerIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => PassengerRouteRoute,
} as any)
const ForgotPasswordIndexRoute = ForgotPasswordIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ForgotPasswordRouteRoute,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRidesIndexRoute = PassengerRidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => PassengerRouteRoute,
} as any)
const PassengerRatingsIndexRoute = PassengerRatingsIndexRouteImport.update({
  id: '/ratings/',
  path: '/ratings/',
  getParentRoute: () => PassengerRouteRoute,
} as any)
const PassengerProfileIndexRoute = PassengerProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => PassengerRouteRoute,
} as any)
const PassengerChatIndexRoute = PassengerChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => PassengerRouteRoute,
} as any)
const DriverRidesIndexRoute = DriverRidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverRequestsIndexRoute = DriverRequestsIndexRouteImport.update({
  id: '/requests/',
  path: '/requests/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverRatingsIndexRoute = DriverRatingsIndexRouteImport.update({
  id: '/ratings/',
  path: '/ratings/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverProfileIndexRoute = DriverProfileIndexRouteImport.update({
  id: '/profile/',
  path: '/profile/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverOfferIndexRoute = DriverOfferIndexRouteImport.update({
  id: '/offer/',
  path: '/offer/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverChatIndexRoute = DriverChatIndexRouteImport.update({
  id: '/chat/',
  path: '/chat/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const CarAddIndexRoute = CarAddIndexRouteImport.update({
  id: '/car/add/',
  path: '/car/add/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersIndexRoute = AdminUsersIndexRouteImport.update({
  id: '/users/',
  path: '/users/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminRidesIndexRoute = AdminRidesIndexRouteImport.update({
  id: '/rides/',
  path: '/rides/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReviewsIndexRoute = AdminReviewsIndexRouteImport.update({
  id: '/reviews/',
  path: '/reviews/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const AdminReportsIndexRoute = AdminReportsIndexRouteImport.update({
  id: '/reports/',
  path: '/reports/',
  getParentRoute: () => AdminRouteRoute,
} as any)
const PassengerRidesSearchIndexRoute =
  PassengerRidesSearchIndexRouteImport.update({
    id: '/rides/search/',
    path: '/rides/search/',
    getParentRoute: () => PassengerRouteRoute,
  } as any)
const DriverRidesRateIndexRoute = DriverRidesRateIndexRouteImport.update({
  id: '/rides/rate/',
  path: '/rides/rate/',
  getParentRoute: () => DriverRouteRoute,
} as any)
const DriverRidesPassengersIndexRoute =
  DriverRidesPassengersIndexRouteImport.update({
    id: '/rides/passengers/',
    path: '/rides/passengers/',
    getParentRoute: () => DriverRouteRoute,
  } as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/driver': typeof DriverRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/passenger': typeof PassengerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/rides': typeof RidesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/rides/': typeof AdminRidesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/car/add/': typeof CarAddIndexRoute
  '/driver/chat/': typeof DriverChatIndexRoute
  '/driver/offer/': typeof DriverOfferIndexRoute
  '/driver/profile/': typeof DriverProfileIndexRoute
  '/driver/ratings/': typeof DriverRatingsIndexRoute
  '/driver/requests/': typeof DriverRequestsIndexRoute
  '/driver/rides/': typeof DriverRidesIndexRoute
  '/passenger/chat/': typeof PassengerChatIndexRoute
  '/passenger/profile/': typeof PassengerProfileIndexRoute
  '/passenger/ratings/': typeof PassengerRatingsIndexRoute
  '/passenger/rides/': typeof PassengerRidesIndexRoute
  '/driver/rides/passengers/': typeof DriverRidesPassengersIndexRoute
  '/driver/rides/rate/': typeof DriverRidesRateIndexRoute
  '/passenger/rides/search/': typeof PassengerRidesSearchIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/rides': typeof RidesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/forgot-password': typeof ForgotPasswordIndexRoute
  '/passenger': typeof PassengerIndexRoute
  '/admin/reports': typeof AdminReportsIndexRoute
  '/admin/reviews': typeof AdminReviewsIndexRoute
  '/admin/rides': typeof AdminRidesIndexRoute
  '/admin/users': typeof AdminUsersIndexRoute
  '/car/add': typeof CarAddIndexRoute
  '/driver/chat': typeof DriverChatIndexRoute
  '/driver/offer': typeof DriverOfferIndexRoute
  '/driver/profile': typeof DriverProfileIndexRoute
  '/driver/ratings': typeof DriverRatingsIndexRoute
  '/driver/requests': typeof DriverRequestsIndexRoute
  '/driver/rides': typeof DriverRidesIndexRoute
  '/passenger/chat': typeof PassengerChatIndexRoute
  '/passenger/profile': typeof PassengerProfileIndexRoute
  '/passenger/ratings': typeof PassengerRatingsIndexRoute
  '/passenger/rides': typeof PassengerRidesIndexRoute
  '/driver/rides/passengers': typeof DriverRidesPassengersIndexRoute
  '/driver/rides/rate': typeof DriverRidesRateIndexRoute
  '/passenger/rides/search': typeof PassengerRidesSearchIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/admin': typeof AdminRouteRouteWithChildren
  '/driver': typeof DriverRouteRouteWithChildren
  '/forgot-password': typeof ForgotPasswordRouteRouteWithChildren
  '/passenger': typeof PassengerRouteRouteWithChildren
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/rides': typeof RidesRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/forgot-password/': typeof ForgotPasswordIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/admin/reports/': typeof AdminReportsIndexRoute
  '/admin/reviews/': typeof AdminReviewsIndexRoute
  '/admin/rides/': typeof AdminRidesIndexRoute
  '/admin/users/': typeof AdminUsersIndexRoute
  '/car/add/': typeof CarAddIndexRoute
  '/driver/chat/': typeof DriverChatIndexRoute
  '/driver/offer/': typeof DriverOfferIndexRoute
  '/driver/profile/': typeof DriverProfileIndexRoute
  '/driver/ratings/': typeof DriverRatingsIndexRoute
  '/driver/requests/': typeof DriverRequestsIndexRoute
  '/driver/rides/': typeof DriverRidesIndexRoute
  '/passenger/chat/': typeof PassengerChatIndexRoute
  '/passenger/profile/': typeof PassengerProfileIndexRoute
  '/passenger/ratings/': typeof PassengerRatingsIndexRoute
  '/passenger/rides/': typeof PassengerRidesIndexRoute
  '/driver/rides/passengers/': typeof DriverRidesPassengersIndexRoute
  '/driver/rides/rate/': typeof DriverRidesRateIndexRoute
  '/passenger/rides/search/': typeof PassengerRidesSearchIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/admin'
    | '/driver'
    | '/forgot-password'
    | '/passenger'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/rides'
    | '/profile/edit'
    | '/admin/'
    | '/driver/'
    | '/forgot-password/'
    | '/passenger/'
    | '/admin/reports/'
    | '/admin/reviews/'
    | '/admin/rides/'
    | '/admin/users/'
    | '/car/add/'
    | '/driver/chat/'
    | '/driver/offer/'
    | '/driver/profile/'
    | '/driver/ratings/'
    | '/driver/requests/'
    | '/driver/rides/'
    | '/passenger/chat/'
    | '/passenger/profile/'
    | '/passenger/ratings/'
    | '/passenger/rides/'
    | '/driver/rides/passengers/'
    | '/driver/rides/rate/'
    | '/passenger/rides/search/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/rides'
    | '/profile/edit'
    | '/admin'
    | '/driver'
    | '/forgot-password'
    | '/passenger'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/rides'
    | '/admin/users'
    | '/car/add'
    | '/driver/chat'
    | '/driver/offer'
    | '/driver/profile'
    | '/driver/ratings'
    | '/driver/requests'
    | '/driver/rides'
    | '/passenger/chat'
    | '/passenger/profile'
    | '/passenger/ratings'
    | '/passenger/rides'
    | '/driver/rides/passengers'
    | '/driver/rides/rate'
    | '/passenger/rides/search'
  id:
    | '__root__'
    | '/'
    | '/admin'
    | '/driver'
    | '/forgot-password'
    | '/passenger'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/rides'
    | '/profile/edit'
    | '/admin/'
    | '/driver/'
    | '/forgot-password/'
    | '/passenger/'
    | '/admin/reports/'
    | '/admin/reviews/'
    | '/admin/rides/'
    | '/admin/users/'
    | '/car/add/'
    | '/driver/chat/'
    | '/driver/offer/'
    | '/driver/profile/'
    | '/driver/ratings/'
    | '/driver/requests/'
    | '/driver/rides/'
    | '/passenger/chat/'
    | '/passenger/profile/'
    | '/passenger/ratings/'
    | '/passenger/rides/'
    | '/driver/rides/passengers/'
    | '/driver/rides/rate/'
    | '/passenger/rides/search/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AdminRouteRoute: typeof AdminRouteRouteWithChildren
  DriverRouteRoute: typeof DriverRouteRouteWithChildren
  ForgotPasswordRouteRoute: typeof ForgotPasswordRouteRouteWithChildren
  PassengerRouteRoute: typeof PassengerRouteRouteWithChildren
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  RidesRoute: typeof RidesRoute
  ProfileEditRoute: typeof ProfileEditRoute
  CarAddIndexRoute: typeof CarAddIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger': {
      id: '/passenger'
      path: '/passenger'
      fullPath: '/passenger'
      preLoaderRoute: typeof PassengerRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver': {
      id: '/driver'
      path: '/driver'
      fullPath: '/driver'
      preLoaderRoute: typeof DriverRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/': {
      id: '/passenger/'
      path: '/'
      fullPath: '/passenger/'
      preLoaderRoute: typeof PassengerIndexRouteImport
      parentRoute: typeof PassengerRouteRoute
    }
    '/forgot-password/': {
      id: '/forgot-password/'
      path: '/'
      fullPath: '/forgot-password/'
      preLoaderRoute: typeof ForgotPasswordIndexRouteImport
      parentRoute: typeof ForgotPasswordRouteRoute
    }
    '/driver/': {
      id: '/driver/'
      path: '/'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/admin/': {
      id: '/admin/'
      path: '/'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/rides/': {
      id: '/passenger/rides/'
      path: '/rides'
      fullPath: '/passenger/rides/'
      preLoaderRoute: typeof PassengerRidesIndexRouteImport
      parentRoute: typeof PassengerRouteRoute
    }
    '/passenger/ratings/': {
      id: '/passenger/ratings/'
      path: '/ratings'
      fullPath: '/passenger/ratings/'
      preLoaderRoute: typeof PassengerRatingsIndexRouteImport
      parentRoute: typeof PassengerRouteRoute
    }
    '/passenger/profile/': {
      id: '/passenger/profile/'
      path: '/profile'
      fullPath: '/passenger/profile/'
      preLoaderRoute: typeof PassengerProfileIndexRouteImport
      parentRoute: typeof PassengerRouteRoute
    }
    '/passenger/chat/': {
      id: '/passenger/chat/'
      path: '/chat'
      fullPath: '/passenger/chat/'
      preLoaderRoute: typeof PassengerChatIndexRouteImport
      parentRoute: typeof PassengerRouteRoute
    }
    '/driver/rides/': {
      id: '/driver/rides/'
      path: '/rides'
      fullPath: '/driver/rides/'
      preLoaderRoute: typeof DriverRidesIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/requests/': {
      id: '/driver/requests/'
      path: '/requests'
      fullPath: '/driver/requests/'
      preLoaderRoute: typeof DriverRequestsIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/ratings/': {
      id: '/driver/ratings/'
      path: '/ratings'
      fullPath: '/driver/ratings/'
      preLoaderRoute: typeof DriverRatingsIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/profile/': {
      id: '/driver/profile/'
      path: '/profile'
      fullPath: '/driver/profile/'
      preLoaderRoute: typeof DriverProfileIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/offer/': {
      id: '/driver/offer/'
      path: '/offer'
      fullPath: '/driver/offer/'
      preLoaderRoute: typeof DriverOfferIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/chat/': {
      id: '/driver/chat/'
      path: '/chat'
      fullPath: '/driver/chat/'
      preLoaderRoute: typeof DriverChatIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/car/add/': {
      id: '/car/add/'
      path: '/car/add'
      fullPath: '/car/add/'
      preLoaderRoute: typeof CarAddIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users/': {
      id: '/admin/users/'
      path: '/users'
      fullPath: '/admin/users/'
      preLoaderRoute: typeof AdminUsersIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/rides/': {
      id: '/admin/rides/'
      path: '/rides'
      fullPath: '/admin/rides/'
      preLoaderRoute: typeof AdminRidesIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reviews/': {
      id: '/admin/reviews/'
      path: '/reviews'
      fullPath: '/admin/reviews/'
      preLoaderRoute: typeof AdminReviewsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/admin/reports/': {
      id: '/admin/reports/'
      path: '/reports'
      fullPath: '/admin/reports/'
      preLoaderRoute: typeof AdminReportsIndexRouteImport
      parentRoute: typeof AdminRouteRoute
    }
    '/passenger/rides/search/': {
      id: '/passenger/rides/search/'
      path: '/rides/search'
      fullPath: '/passenger/rides/search/'
      preLoaderRoute: typeof PassengerRidesSearchIndexRouteImport
      parentRoute: typeof PassengerRouteRoute
    }
    '/driver/rides/rate/': {
      id: '/driver/rides/rate/'
      path: '/rides/rate'
      fullPath: '/driver/rides/rate/'
      preLoaderRoute: typeof DriverRidesRateIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
    '/driver/rides/passengers/': {
      id: '/driver/rides/passengers/'
      path: '/rides/passengers'
      fullPath: '/driver/rides/passengers/'
      preLoaderRoute: typeof DriverRidesPassengersIndexRouteImport
      parentRoute: typeof DriverRouteRoute
    }
  }
}

interface AdminRouteRouteChildren {
  AdminIndexRoute: typeof AdminIndexRoute
  AdminReportsIndexRoute: typeof AdminReportsIndexRoute
  AdminReviewsIndexRoute: typeof AdminReviewsIndexRoute
  AdminRidesIndexRoute: typeof AdminRidesIndexRoute
  AdminUsersIndexRoute: typeof AdminUsersIndexRoute
}

const AdminRouteRouteChildren: AdminRouteRouteChildren = {
  AdminIndexRoute: AdminIndexRoute,
  AdminReportsIndexRoute: AdminReportsIndexRoute,
  AdminReviewsIndexRoute: AdminReviewsIndexRoute,
  AdminRidesIndexRoute: AdminRidesIndexRoute,
  AdminUsersIndexRoute: AdminUsersIndexRoute,
}

const AdminRouteRouteWithChildren = AdminRouteRoute._addFileChildren(
  AdminRouteRouteChildren,
)

interface DriverRouteRouteChildren {
  DriverIndexRoute: typeof DriverIndexRoute
  DriverChatIndexRoute: typeof DriverChatIndexRoute
  DriverOfferIndexRoute: typeof DriverOfferIndexRoute
  DriverProfileIndexRoute: typeof DriverProfileIndexRoute
  DriverRatingsIndexRoute: typeof DriverRatingsIndexRoute
  DriverRequestsIndexRoute: typeof DriverRequestsIndexRoute
  DriverRidesIndexRoute: typeof DriverRidesIndexRoute
  DriverRidesPassengersIndexRoute: typeof DriverRidesPassengersIndexRoute
  DriverRidesRateIndexRoute: typeof DriverRidesRateIndexRoute
}

const DriverRouteRouteChildren: DriverRouteRouteChildren = {
  DriverIndexRoute: DriverIndexRoute,
  DriverChatIndexRoute: DriverChatIndexRoute,
  DriverOfferIndexRoute: DriverOfferIndexRoute,
  DriverProfileIndexRoute: DriverProfileIndexRoute,
  DriverRatingsIndexRoute: DriverRatingsIndexRoute,
  DriverRequestsIndexRoute: DriverRequestsIndexRoute,
  DriverRidesIndexRoute: DriverRidesIndexRoute,
  DriverRidesPassengersIndexRoute: DriverRidesPassengersIndexRoute,
  DriverRidesRateIndexRoute: DriverRidesRateIndexRoute,
}

const DriverRouteRouteWithChildren = DriverRouteRoute._addFileChildren(
  DriverRouteRouteChildren,
)

interface ForgotPasswordRouteRouteChildren {
  ForgotPasswordIndexRoute: typeof ForgotPasswordIndexRoute
}

const ForgotPasswordRouteRouteChildren: ForgotPasswordRouteRouteChildren = {
  ForgotPasswordIndexRoute: ForgotPasswordIndexRoute,
}

const ForgotPasswordRouteRouteWithChildren =
  ForgotPasswordRouteRoute._addFileChildren(ForgotPasswordRouteRouteChildren)

interface PassengerRouteRouteChildren {
  PassengerIndexRoute: typeof PassengerIndexRoute
  PassengerChatIndexRoute: typeof PassengerChatIndexRoute
  PassengerProfileIndexRoute: typeof PassengerProfileIndexRoute
  PassengerRatingsIndexRoute: typeof PassengerRatingsIndexRoute
  PassengerRidesIndexRoute: typeof PassengerRidesIndexRoute
  PassengerRidesSearchIndexRoute: typeof PassengerRidesSearchIndexRoute
}

const PassengerRouteRouteChildren: PassengerRouteRouteChildren = {
  PassengerIndexRoute: PassengerIndexRoute,
  PassengerChatIndexRoute: PassengerChatIndexRoute,
  PassengerProfileIndexRoute: PassengerProfileIndexRoute,
  PassengerRatingsIndexRoute: PassengerRatingsIndexRoute,
  PassengerRidesIndexRoute: PassengerRidesIndexRoute,
  PassengerRidesSearchIndexRoute: PassengerRidesSearchIndexRoute,
}

const PassengerRouteRouteWithChildren = PassengerRouteRoute._addFileChildren(
  PassengerRouteRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AdminRouteRoute: AdminRouteRouteWithChildren,
  DriverRouteRoute: DriverRouteRouteWithChildren,
  ForgotPasswordRouteRoute: ForgotPasswordRouteRouteWithChildren,
  PassengerRouteRoute: PassengerRouteRouteWithChildren,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  RidesRoute: RidesRoute,
  ProfileEditRoute: ProfileEditRoute,
  CarAddIndexRoute: CarAddIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
