/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as RidesRouteImport } from './routes/rides'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as OnboardingRouteImport } from './routes/onboarding'
import { Route as LoginRouteImport } from './routes/login'
import { Route as ForgotPasswordRouteImport } from './routes/forgot-password'
import { Route as IndexRouteImport } from './routes/index'
import { Route as PassengerIndexRouteImport } from './routes/passenger/index'
import { Route as DriverIndexRouteImport } from './routes/driver/index'
import { Route as AdminIndexRouteImport } from './routes/admin/index'
import { Route as ProfileEditRouteImport } from './routes/profile/edit'
import { Route as PassengerRatingsRouteImport } from './routes/passenger/ratings'
import { Route as PassengerProfileRouteImport } from './routes/passenger/profile'
import { Route as PassengerChatRouteImport } from './routes/passenger/chat'
import { Route as DriverRequestsRouteImport } from './routes/driver/requests'
import { Route as DriverRatingsRouteImport } from './routes/driver/ratings'
import { Route as DriverProfileRouteImport } from './routes/driver/profile'
import { Route as DriverOfferRouteImport } from './routes/driver/offer'
import { Route as DriverChatRouteImport } from './routes/driver/chat'
import { Route as CarAddRouteImport } from './routes/car/add'
import { Route as AdminUsersRouteImport } from './routes/admin/users'
import { Route as AdminRidesRouteImport } from './routes/admin/rides'
import { Route as AdminReviewsRouteImport } from './routes/admin/reviews'
import { Route as AdminReportsRouteImport } from './routes/admin/reports'
import { Route as PassengerRidesIndexRouteImport } from './routes/passenger/rides/index'
import { Route as DriverRidesIndexRouteImport } from './routes/driver/rides/index'
import { Route as PassengerRidesSearchRouteImport } from './routes/passenger/rides/search'
import { Route as DriverRidesRateRouteImport } from './routes/driver/rides/rate'
import { Route as DriverRidesPassengersRouteImport } from './routes/driver/rides/passengers'

const RidesRoute = RidesRouteImport.update({
  id: '/rides',
  path: '/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const OnboardingRoute = OnboardingRouteImport.update({
  id: '/onboarding',
  path: '/onboarding',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const ForgotPasswordRoute = ForgotPasswordRouteImport.update({
  id: '/forgot-password',
  path: '/forgot-password',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerIndexRoute = PassengerIndexRouteImport.update({
  id: '/passenger/',
  path: '/passenger/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverIndexRoute = DriverIndexRouteImport.update({
  id: '/driver/',
  path: '/driver/',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminIndexRoute = AdminIndexRouteImport.update({
  id: '/admin/',
  path: '/admin/',
  getParentRoute: () => rootRouteImport,
} as any)
const ProfileEditRoute = ProfileEditRouteImport.update({
  id: '/profile/edit',
  path: '/profile/edit',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRatingsRoute = PassengerRatingsRouteImport.update({
  id: '/passenger/ratings',
  path: '/passenger/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerProfileRoute = PassengerProfileRouteImport.update({
  id: '/passenger/profile',
  path: '/passenger/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerChatRoute = PassengerChatRouteImport.update({
  id: '/passenger/chat',
  path: '/passenger/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRequestsRoute = DriverRequestsRouteImport.update({
  id: '/driver/requests',
  path: '/driver/requests',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRatingsRoute = DriverRatingsRouteImport.update({
  id: '/driver/ratings',
  path: '/driver/ratings',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverProfileRoute = DriverProfileRouteImport.update({
  id: '/driver/profile',
  path: '/driver/profile',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverOfferRoute = DriverOfferRouteImport.update({
  id: '/driver/offer',
  path: '/driver/offer',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverChatRoute = DriverChatRouteImport.update({
  id: '/driver/chat',
  path: '/driver/chat',
  getParentRoute: () => rootRouteImport,
} as any)
const CarAddRoute = CarAddRouteImport.update({
  id: '/car/add',
  path: '/car/add',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminUsersRoute = AdminUsersRouteImport.update({
  id: '/admin/users',
  path: '/admin/users',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRidesRoute = AdminRidesRouteImport.update({
  id: '/admin/rides',
  path: '/admin/rides',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReviewsRoute = AdminReviewsRouteImport.update({
  id: '/admin/reviews',
  path: '/admin/reviews',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminReportsRoute = AdminReportsRouteImport.update({
  id: '/admin/reports',
  path: '/admin/reports',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRidesIndexRoute = PassengerRidesIndexRouteImport.update({
  id: '/passenger/rides/',
  path: '/passenger/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRidesIndexRoute = DriverRidesIndexRouteImport.update({
  id: '/driver/rides/',
  path: '/driver/rides/',
  getParentRoute: () => rootRouteImport,
} as any)
const PassengerRidesSearchRoute = PassengerRidesSearchRouteImport.update({
  id: '/passenger/rides/search',
  path: '/passenger/rides/search',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRidesRateRoute = DriverRidesRateRouteImport.update({
  id: '/driver/rides/rate',
  path: '/driver/rides/rate',
  getParentRoute: () => rootRouteImport,
} as any)
const DriverRidesPassengersRoute = DriverRidesPassengersRouteImport.update({
  id: '/driver/rides/passengers',
  path: '/driver/rides/passengers',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/rides': typeof RidesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/users': typeof AdminUsersRoute
  '/car/add': typeof CarAddRoute
  '/driver/chat': typeof DriverChatRoute
  '/driver/offer': typeof DriverOfferRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/ratings': typeof DriverRatingsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/passenger/chat': typeof PassengerChatRoute
  '/passenger/profile': typeof PassengerProfileRoute
  '/passenger/ratings': typeof PassengerRatingsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/driver/rides/passengers': typeof DriverRidesPassengersRoute
  '/driver/rides/rate': typeof DriverRidesRateRoute
  '/passenger/rides/search': typeof PassengerRidesSearchRoute
  '/driver/rides/': typeof DriverRidesIndexRoute
  '/passenger/rides/': typeof PassengerRidesIndexRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/rides': typeof RidesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/users': typeof AdminUsersRoute
  '/car/add': typeof CarAddRoute
  '/driver/chat': typeof DriverChatRoute
  '/driver/offer': typeof DriverOfferRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/ratings': typeof DriverRatingsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/passenger/chat': typeof PassengerChatRoute
  '/passenger/profile': typeof PassengerProfileRoute
  '/passenger/ratings': typeof PassengerRatingsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin': typeof AdminIndexRoute
  '/driver': typeof DriverIndexRoute
  '/passenger': typeof PassengerIndexRoute
  '/driver/rides/passengers': typeof DriverRidesPassengersRoute
  '/driver/rides/rate': typeof DriverRidesRateRoute
  '/passenger/rides/search': typeof PassengerRidesSearchRoute
  '/driver/rides': typeof DriverRidesIndexRoute
  '/passenger/rides': typeof PassengerRidesIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/forgot-password': typeof ForgotPasswordRoute
  '/login': typeof LoginRoute
  '/onboarding': typeof OnboardingRoute
  '/register': typeof RegisterRoute
  '/rides': typeof RidesRoute
  '/admin/reports': typeof AdminReportsRoute
  '/admin/reviews': typeof AdminReviewsRoute
  '/admin/rides': typeof AdminRidesRoute
  '/admin/users': typeof AdminUsersRoute
  '/car/add': typeof CarAddRoute
  '/driver/chat': typeof DriverChatRoute
  '/driver/offer': typeof DriverOfferRoute
  '/driver/profile': typeof DriverProfileRoute
  '/driver/ratings': typeof DriverRatingsRoute
  '/driver/requests': typeof DriverRequestsRoute
  '/passenger/chat': typeof PassengerChatRoute
  '/passenger/profile': typeof PassengerProfileRoute
  '/passenger/ratings': typeof PassengerRatingsRoute
  '/profile/edit': typeof ProfileEditRoute
  '/admin/': typeof AdminIndexRoute
  '/driver/': typeof DriverIndexRoute
  '/passenger/': typeof PassengerIndexRoute
  '/driver/rides/passengers': typeof DriverRidesPassengersRoute
  '/driver/rides/rate': typeof DriverRidesRateRoute
  '/passenger/rides/search': typeof PassengerRidesSearchRoute
  '/driver/rides/': typeof DriverRidesIndexRoute
  '/passenger/rides/': typeof PassengerRidesIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/rides'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/rides'
    | '/admin/users'
    | '/car/add'
    | '/driver/chat'
    | '/driver/offer'
    | '/driver/profile'
    | '/driver/ratings'
    | '/driver/requests'
    | '/passenger/chat'
    | '/passenger/profile'
    | '/passenger/ratings'
    | '/profile/edit'
    | '/admin/'
    | '/driver/'
    | '/passenger/'
    | '/driver/rides/passengers'
    | '/driver/rides/rate'
    | '/passenger/rides/search'
    | '/driver/rides/'
    | '/passenger/rides/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/rides'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/rides'
    | '/admin/users'
    | '/car/add'
    | '/driver/chat'
    | '/driver/offer'
    | '/driver/profile'
    | '/driver/ratings'
    | '/driver/requests'
    | '/passenger/chat'
    | '/passenger/profile'
    | '/passenger/ratings'
    | '/profile/edit'
    | '/admin'
    | '/driver'
    | '/passenger'
    | '/driver/rides/passengers'
    | '/driver/rides/rate'
    | '/passenger/rides/search'
    | '/driver/rides'
    | '/passenger/rides'
  id:
    | '__root__'
    | '/'
    | '/forgot-password'
    | '/login'
    | '/onboarding'
    | '/register'
    | '/rides'
    | '/admin/reports'
    | '/admin/reviews'
    | '/admin/rides'
    | '/admin/users'
    | '/car/add'
    | '/driver/chat'
    | '/driver/offer'
    | '/driver/profile'
    | '/driver/ratings'
    | '/driver/requests'
    | '/passenger/chat'
    | '/passenger/profile'
    | '/passenger/ratings'
    | '/profile/edit'
    | '/admin/'
    | '/driver/'
    | '/passenger/'
    | '/driver/rides/passengers'
    | '/driver/rides/rate'
    | '/passenger/rides/search'
    | '/driver/rides/'
    | '/passenger/rides/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  ForgotPasswordRoute: typeof ForgotPasswordRoute
  LoginRoute: typeof LoginRoute
  OnboardingRoute: typeof OnboardingRoute
  RegisterRoute: typeof RegisterRoute
  RidesRoute: typeof RidesRoute
  AdminReportsRoute: typeof AdminReportsRoute
  AdminReviewsRoute: typeof AdminReviewsRoute
  AdminRidesRoute: typeof AdminRidesRoute
  AdminUsersRoute: typeof AdminUsersRoute
  CarAddRoute: typeof CarAddRoute
  DriverChatRoute: typeof DriverChatRoute
  DriverOfferRoute: typeof DriverOfferRoute
  DriverProfileRoute: typeof DriverProfileRoute
  DriverRatingsRoute: typeof DriverRatingsRoute
  DriverRequestsRoute: typeof DriverRequestsRoute
  PassengerChatRoute: typeof PassengerChatRoute
  PassengerProfileRoute: typeof PassengerProfileRoute
  PassengerRatingsRoute: typeof PassengerRatingsRoute
  ProfileEditRoute: typeof ProfileEditRoute
  AdminIndexRoute: typeof AdminIndexRoute
  DriverIndexRoute: typeof DriverIndexRoute
  PassengerIndexRoute: typeof PassengerIndexRoute
  DriverRidesPassengersRoute: typeof DriverRidesPassengersRoute
  DriverRidesRateRoute: typeof DriverRidesRateRoute
  PassengerRidesSearchRoute: typeof PassengerRidesSearchRoute
  DriverRidesIndexRoute: typeof DriverRidesIndexRoute
  PassengerRidesIndexRoute: typeof PassengerRidesIndexRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/rides': {
      id: '/rides'
      path: '/rides'
      fullPath: '/rides'
      preLoaderRoute: typeof RidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/onboarding': {
      id: '/onboarding'
      path: '/onboarding'
      fullPath: '/onboarding'
      preLoaderRoute: typeof OnboardingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forgot-password': {
      id: '/forgot-password'
      path: '/forgot-password'
      fullPath: '/forgot-password'
      preLoaderRoute: typeof ForgotPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/': {
      id: '/passenger/'
      path: '/passenger'
      fullPath: '/passenger/'
      preLoaderRoute: typeof PassengerIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/': {
      id: '/driver/'
      path: '/driver'
      fullPath: '/driver/'
      preLoaderRoute: typeof DriverIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/': {
      id: '/admin/'
      path: '/admin'
      fullPath: '/admin/'
      preLoaderRoute: typeof AdminIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/profile/edit': {
      id: '/profile/edit'
      path: '/profile/edit'
      fullPath: '/profile/edit'
      preLoaderRoute: typeof ProfileEditRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/ratings': {
      id: '/passenger/ratings'
      path: '/passenger/ratings'
      fullPath: '/passenger/ratings'
      preLoaderRoute: typeof PassengerRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/profile': {
      id: '/passenger/profile'
      path: '/passenger/profile'
      fullPath: '/passenger/profile'
      preLoaderRoute: typeof PassengerProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/chat': {
      id: '/passenger/chat'
      path: '/passenger/chat'
      fullPath: '/passenger/chat'
      preLoaderRoute: typeof PassengerChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/requests': {
      id: '/driver/requests'
      path: '/driver/requests'
      fullPath: '/driver/requests'
      preLoaderRoute: typeof DriverRequestsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/ratings': {
      id: '/driver/ratings'
      path: '/driver/ratings'
      fullPath: '/driver/ratings'
      preLoaderRoute: typeof DriverRatingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/profile': {
      id: '/driver/profile'
      path: '/driver/profile'
      fullPath: '/driver/profile'
      preLoaderRoute: typeof DriverProfileRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/offer': {
      id: '/driver/offer'
      path: '/driver/offer'
      fullPath: '/driver/offer'
      preLoaderRoute: typeof DriverOfferRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/chat': {
      id: '/driver/chat'
      path: '/driver/chat'
      fullPath: '/driver/chat'
      preLoaderRoute: typeof DriverChatRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/car/add': {
      id: '/car/add'
      path: '/car/add'
      fullPath: '/car/add'
      preLoaderRoute: typeof CarAddRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/users': {
      id: '/admin/users'
      path: '/admin/users'
      fullPath: '/admin/users'
      preLoaderRoute: typeof AdminUsersRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/rides': {
      id: '/admin/rides'
      path: '/admin/rides'
      fullPath: '/admin/rides'
      preLoaderRoute: typeof AdminRidesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reviews': {
      id: '/admin/reviews'
      path: '/admin/reviews'
      fullPath: '/admin/reviews'
      preLoaderRoute: typeof AdminReviewsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin/reports': {
      id: '/admin/reports'
      path: '/admin/reports'
      fullPath: '/admin/reports'
      preLoaderRoute: typeof AdminReportsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/rides/': {
      id: '/passenger/rides/'
      path: '/passenger/rides'
      fullPath: '/passenger/rides/'
      preLoaderRoute: typeof PassengerRidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/rides/': {
      id: '/driver/rides/'
      path: '/driver/rides'
      fullPath: '/driver/rides/'
      preLoaderRoute: typeof DriverRidesIndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/passenger/rides/search': {
      id: '/passenger/rides/search'
      path: '/passenger/rides/search'
      fullPath: '/passenger/rides/search'
      preLoaderRoute: typeof PassengerRidesSearchRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/rides/rate': {
      id: '/driver/rides/rate'
      path: '/driver/rides/rate'
      fullPath: '/driver/rides/rate'
      preLoaderRoute: typeof DriverRidesRateRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/driver/rides/passengers': {
      id: '/driver/rides/passengers'
      path: '/driver/rides/passengers'
      fullPath: '/driver/rides/passengers'
      preLoaderRoute: typeof DriverRidesPassengersRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  ForgotPasswordRoute: ForgotPasswordRoute,
  LoginRoute: LoginRoute,
  OnboardingRoute: OnboardingRoute,
  RegisterRoute: RegisterRoute,
  RidesRoute: RidesRoute,
  AdminReportsRoute: AdminReportsRoute,
  AdminReviewsRoute: AdminReviewsRoute,
  AdminRidesRoute: AdminRidesRoute,
  AdminUsersRoute: AdminUsersRoute,
  CarAddRoute: CarAddRoute,
  DriverChatRoute: DriverChatRoute,
  DriverOfferRoute: DriverOfferRoute,
  DriverProfileRoute: DriverProfileRoute,
  DriverRatingsRoute: DriverRatingsRoute,
  DriverRequestsRoute: DriverRequestsRoute,
  PassengerChatRoute: PassengerChatRoute,
  PassengerProfileRoute: PassengerProfileRoute,
  PassengerRatingsRoute: PassengerRatingsRoute,
  ProfileEditRoute: ProfileEditRoute,
  AdminIndexRoute: AdminIndexRoute,
  DriverIndexRoute: DriverIndexRoute,
  PassengerIndexRoute: PassengerIndexRoute,
  DriverRidesPassengersRoute: DriverRidesPassengersRoute,
  DriverRidesRateRoute: DriverRidesRateRoute,
  PassengerRidesSearchRoute: PassengerRidesSearchRoute,
  DriverRidesIndexRoute: DriverRidesIndexRoute,
  PassengerRidesIndexRoute: PassengerRidesIndexRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
