/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    ErrorResponse,
    GetNotificationsParams,
    NotificationList,
    NotificationReadResponse,
    NotificationsReadAllResponse,
    UnreadCountResponse,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns the authenticated user's notifications (newest first), optionally paginated with a `before` cursor
 */
export const getGetNotificationsUrl = (params: GetNotificationsParams) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/notifications/?${stringifiedParams}`
        : `/notifications/`;
};

export const getNotifications = async (
    params: GetNotificationsParams,
    options?: RequestInit
): Promise<NotificationList> => {
    return apiFetcher<NotificationList>(getGetNotificationsUrl(params), {
        ...options,
        method: "GET",
    });
};

export const getGetNotificationsQueryKey = (
    params?: GetNotificationsParams
) => {
    return [`/notifications/`, ...(params ? [params] : [])] as const;
};

export const getGetNotificationsQueryOptions = <
    TData = Awaited<ReturnType<typeof getNotifications>>,
    TError = ErrorResponse,
>(
    params: GetNotificationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotifications>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetNotificationsQueryKey(params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getNotifications>>
    > = () => getNotifications(params, requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getNotifications>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotificationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getNotifications>>
>;
export type GetNotificationsQueryError = ErrorResponse;

export function useGetNotifications<
    TData = Awaited<ReturnType<typeof getNotifications>>,
    TError = ErrorResponse,
>(
    params: GetNotificationsParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotifications>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getNotifications>>,
                    TError,
                    Awaited<ReturnType<typeof getNotifications>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNotifications<
    TData = Awaited<ReturnType<typeof getNotifications>>,
    TError = ErrorResponse,
>(
    params: GetNotificationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotifications>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getNotifications>>,
                    TError,
                    Awaited<ReturnType<typeof getNotifications>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNotifications<
    TData = Awaited<ReturnType<typeof getNotifications>>,
    TError = ErrorResponse,
>(
    params: GetNotificationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotifications>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetNotifications<
    TData = Awaited<ReturnType<typeof getNotifications>>,
    TError = ErrorResponse,
>(
    params: GetNotificationsParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotifications>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetNotificationsQueryOptions(params, options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Returns how many of the authenticated user's notifications are unread
 */
export const getGetNotificationsUnreadCountUrl = () => {
    return `/notifications/unread-count`;
};

export const getNotificationsUnreadCount = async (
    options?: RequestInit
): Promise<UnreadCountResponse> => {
    return apiFetcher<UnreadCountResponse>(
        getGetNotificationsUnreadCountUrl(),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getGetNotificationsUnreadCountQueryKey = () => {
    return [`/notifications/unread-count`] as const;
};

export const getGetNotificationsUnreadCountQueryOptions = <
    TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ?? getGetNotificationsUnreadCountQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getNotificationsUnreadCount>>
    > = () => getNotificationsUnreadCount(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetNotificationsUnreadCountQueryResult = NonNullable<
    Awaited<ReturnType<typeof getNotificationsUnreadCount>>
>;
export type GetNotificationsUnreadCountQueryError = ErrorResponse;

export function useGetNotificationsUnreadCount<
    TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
                    TError,
                    Awaited<ReturnType<typeof getNotificationsUnreadCount>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNotificationsUnreadCount<
    TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
                    TError,
                    Awaited<ReturnType<typeof getNotificationsUnreadCount>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetNotificationsUnreadCount<
    TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetNotificationsUnreadCount<
    TData = Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getNotificationsUnreadCount>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetNotificationsUnreadCountQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Marks all of the authenticated user's notifications as read; returns how many were updated
 */
export const getPatchNotificationsReadAllUrl = () => {
    return `/notifications/read-all`;
};

export const patchNotificationsReadAll = async (
    options?: RequestInit
): Promise<NotificationsReadAllResponse> => {
    return apiFetcher<NotificationsReadAllResponse>(
        getPatchNotificationsReadAllUrl(),
        {
            ...options,
            method: "PATCH",
        }
    );
};

export const getPatchNotificationsReadAllMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchNotificationsReadAll>>,
        TError,
        void,
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchNotificationsReadAll>>,
    TError,
    void,
    TContext
> => {
    const mutationKey = ["patchNotificationsReadAll"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchNotificationsReadAll>>,
        void
    > = () => {
        return patchNotificationsReadAll(requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchNotificationsReadAllMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchNotificationsReadAll>>
>;

export type PatchNotificationsReadAllMutationError = ErrorResponse;

export const usePatchNotificationsReadAll = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchNotificationsReadAll>>,
            TError,
            void,
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchNotificationsReadAll>>,
    TError,
    void,
    TContext
> => {
    const mutationOptions =
        getPatchNotificationsReadAllMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Marks a single notification as read. Idempotent — re-reading returns the existing readAt
 */
export const getPatchNotificationsByIdReadUrl = (id: string) => {
    return `/notifications/${id}/read`;
};

export const patchNotificationsByIdRead = async (
    id: string,
    options?: RequestInit
): Promise<NotificationReadResponse> => {
    return apiFetcher<NotificationReadResponse>(
        getPatchNotificationsByIdReadUrl(id),
        {
            ...options,
            method: "PATCH",
        }
    );
};

export const getPatchNotificationsByIdReadMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchNotificationsByIdRead>>,
        TError,
        { id: string },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchNotificationsByIdRead>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["patchNotificationsByIdRead"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchNotificationsByIdRead>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {};

        return patchNotificationsByIdRead(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchNotificationsByIdReadMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchNotificationsByIdRead>>
>;

export type PatchNotificationsByIdReadMutationError = ErrorResponse;

export const usePatchNotificationsByIdRead = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchNotificationsByIdRead>>,
            TError,
            { id: string },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchNotificationsByIdRead>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationOptions =
        getPatchNotificationsByIdReadMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
