/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    BlockActionResponse,
    BlockList,
    CreateBlockBody,
    ErrorResponse,
    UnblockResponse,
    UserId,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Lists the users the authenticated user has blocked.
 */
export const getGetBlocksUrl = () => {
    return `/blocks/`;
};

export const getBlocks = async (options?: RequestInit): Promise<BlockList> => {
    return apiFetcher<BlockList>(getGetBlocksUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetBlocksQueryKey = () => {
    return [`/blocks/`] as const;
};

export const getGetBlocksQueryOptions = <
    TData = Awaited<ReturnType<typeof getBlocks>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getBlocks>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetBlocksQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getBlocks>>> = () =>
        getBlocks(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getBlocks>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetBlocksQueryResult = NonNullable<
    Awaited<ReturnType<typeof getBlocks>>
>;
export type GetBlocksQueryError = ErrorResponse;

export function useGetBlocks<
    TData = Awaited<ReturnType<typeof getBlocks>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getBlocks>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getBlocks>>,
                    TError,
                    Awaited<ReturnType<typeof getBlocks>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlocks<
    TData = Awaited<ReturnType<typeof getBlocks>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getBlocks>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getBlocks>>,
                    TError,
                    Awaited<ReturnType<typeof getBlocks>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetBlocks<
    TData = Awaited<ReturnType<typeof getBlocks>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getBlocks>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetBlocks<
    TData = Awaited<ReturnType<typeof getBlocks>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getBlocks>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetBlocksQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Blocks a user. Idempotent — re-blocking returns the existing block. Stops chat, bookings, and search visibility between the two.
 */
export const getPostBlocksUrl = () => {
    return `/blocks/`;
};

export const postBlocks = async (
    createBlockBody: CreateBlockBody,
    options?: RequestInit
): Promise<BlockActionResponse> => {
    return apiFetcher<BlockActionResponse>(getPostBlocksUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createBlockBody),
    });
};

export const getPostBlocksMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postBlocks>>,
        TError,
        { data: CreateBlockBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postBlocks>>,
    TError,
    { data: CreateBlockBody },
    TContext
> => {
    const mutationKey = ["postBlocks"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postBlocks>>,
        { data: CreateBlockBody }
    > = (props) => {
        const { data } = props ?? {};

        return postBlocks(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostBlocksMutationResult = NonNullable<
    Awaited<ReturnType<typeof postBlocks>>
>;
export type PostBlocksMutationBody = CreateBlockBody;
export type PostBlocksMutationError = ErrorResponse;

export const usePostBlocks = <TError = ErrorResponse, TContext = unknown>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof postBlocks>>,
            TError,
            { data: CreateBlockBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof postBlocks>>,
    TError,
    { data: CreateBlockBody },
    TContext
> => {
    const mutationOptions = getPostBlocksMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Removes a user from the authenticated user's block list.
 */
export const getDeleteBlocksByBlockedUserIdUrl = (blockedUserId: UserId) => {
    return `/blocks/${blockedUserId}`;
};

export const deleteBlocksByBlockedUserId = async (
    blockedUserId: UserId,
    options?: RequestInit
): Promise<UnblockResponse> => {
    return apiFetcher<UnblockResponse>(
        getDeleteBlocksByBlockedUserIdUrl(blockedUserId),
        {
            ...options,
            method: "DELETE",
        }
    );
};

export const getDeleteBlocksByBlockedUserIdMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof deleteBlocksByBlockedUserId>>,
        TError,
        { blockedUserId: UserId },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof deleteBlocksByBlockedUserId>>,
    TError,
    { blockedUserId: UserId },
    TContext
> => {
    const mutationKey = ["deleteBlocksByBlockedUserId"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof deleteBlocksByBlockedUserId>>,
        { blockedUserId: UserId }
    > = (props) => {
        const { blockedUserId } = props ?? {};

        return deleteBlocksByBlockedUserId(blockedUserId, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type DeleteBlocksByBlockedUserIdMutationResult = NonNullable<
    Awaited<ReturnType<typeof deleteBlocksByBlockedUserId>>
>;

export type DeleteBlocksByBlockedUserIdMutationError = ErrorResponse;

export const useDeleteBlocksByBlockedUserId = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof deleteBlocksByBlockedUserId>>,
            TError,
            { blockedUserId: UserId },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof deleteBlocksByBlockedUserId>>,
    TError,
    { blockedUserId: UserId },
    TContext
> => {
    const mutationOptions =
        getDeleteBlocksByBlockedUserIdMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
