/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    ConversationActionResponse,
    ConversationList,
    ConversationReadResponse,
    CreateConversationBody,
    ErrorResponse,
    GetConversationsByIdMessagesParams,
    Message,
    MessageList,
    SendMessageBody,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns all conversations the authenticated user takes part in, with the latest message and unread count
 */
export const getGetConversationsUrl = () => {
    return `/conversations/`;
};

export const getConversations = async (
    options?: RequestInit
): Promise<ConversationList> => {
    return apiFetcher<ConversationList>(getGetConversationsUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetConversationsQueryKey = () => {
    return [`/conversations/`] as const;
};

export const getGetConversationsQueryOptions = <
    TData = Awaited<ReturnType<typeof getConversations>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<
            Awaited<ReturnType<typeof getConversations>>,
            TError,
            TData
        >
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetConversationsQueryKey();

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getConversations>>
    > = () => getConversations(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getConversations>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConversationsQueryResult = NonNullable<
    Awaited<ReturnType<typeof getConversations>>
>;
export type GetConversationsQueryError = ErrorResponse;

export function useGetConversations<
    TData = Awaited<ReturnType<typeof getConversations>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversations>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getConversations>>,
                    TError,
                    Awaited<ReturnType<typeof getConversations>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConversations<
    TData = Awaited<ReturnType<typeof getConversations>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversations>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getConversations>>,
                    TError,
                    Awaited<ReturnType<typeof getConversations>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConversations<
    TData = Awaited<ReturnType<typeof getConversations>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetConversations<
    TData = Awaited<ReturnType<typeof getConversations>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversations>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetConversationsQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Opens (or reuses) the conversation for a booking between its driver and passenger
 */
export const getPostConversationsUrl = () => {
    return `/conversations/`;
};

export const postConversations = async (
    createConversationBody: CreateConversationBody,
    options?: RequestInit
): Promise<ConversationActionResponse> => {
    return apiFetcher<ConversationActionResponse>(getPostConversationsUrl(), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(createConversationBody),
    });
};

export const getPostConversationsMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postConversations>>,
        TError,
        { data: CreateConversationBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postConversations>>,
    TError,
    { data: CreateConversationBody },
    TContext
> => {
    const mutationKey = ["postConversations"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postConversations>>,
        { data: CreateConversationBody }
    > = (props) => {
        const { data } = props ?? {};

        return postConversations(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostConversationsMutationResult = NonNullable<
    Awaited<ReturnType<typeof postConversations>>
>;
export type PostConversationsMutationBody = CreateConversationBody;
export type PostConversationsMutationError = ErrorResponse;

export const usePostConversations = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof postConversations>>,
            TError,
            { data: CreateConversationBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof postConversations>>,
    TError,
    { data: CreateConversationBody },
    TContext
> => {
    const mutationOptions = getPostConversationsMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Returns messages in a conversation (oldest first), optionally paginated with a `before` cursor
 */
export const getGetConversationsByIdMessagesUrl = (
    id: string,
    params: GetConversationsByIdMessagesParams
) => {
    const normalizedParams = new URLSearchParams();

    Object.entries(params || {}).forEach(([key, value]) => {
        if (value !== undefined) {
            normalizedParams.append(
                key,
                value === null ? "null" : value.toString()
            );
        }
    });

    const stringifiedParams = normalizedParams.toString();

    return stringifiedParams.length > 0
        ? `/conversations/${id}/messages?${stringifiedParams}`
        : `/conversations/${id}/messages`;
};

export const getConversationsByIdMessages = async (
    id: string,
    params: GetConversationsByIdMessagesParams,
    options?: RequestInit
): Promise<MessageList> => {
    return apiFetcher<MessageList>(
        getGetConversationsByIdMessagesUrl(id, params),
        {
            ...options,
            method: "GET",
        }
    );
};

export const getGetConversationsByIdMessagesQueryKey = (
    id?: string,
    params?: GetConversationsByIdMessagesParams
) => {
    return [
        `/conversations/${id}/messages`,
        ...(params ? [params] : []),
    ] as const;
};

export const getGetConversationsByIdMessagesQueryOptions = <
    TData = Awaited<ReturnType<typeof getConversationsByIdMessages>>,
    TError = ErrorResponse,
>(
    id: string,
    params: GetConversationsByIdMessagesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversationsByIdMessages>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    }
) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey =
        queryOptions?.queryKey ??
        getGetConversationsByIdMessagesQueryKey(id, params);

    const queryFn: QueryFunction<
        Awaited<ReturnType<typeof getConversationsByIdMessages>>
    > = () => getConversationsByIdMessages(id, params, requestOptions);

    return {
        queryKey,
        queryFn,
        enabled: !!id,
        ...queryOptions,
    } as UseQueryOptions<
        Awaited<ReturnType<typeof getConversationsByIdMessages>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetConversationsByIdMessagesQueryResult = NonNullable<
    Awaited<ReturnType<typeof getConversationsByIdMessages>>
>;
export type GetConversationsByIdMessagesQueryError = ErrorResponse;

export function useGetConversationsByIdMessages<
    TData = Awaited<ReturnType<typeof getConversationsByIdMessages>>,
    TError = ErrorResponse,
>(
    id: string,
    params: GetConversationsByIdMessagesParams,
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversationsByIdMessages>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getConversationsByIdMessages>>,
                    TError,
                    Awaited<ReturnType<typeof getConversationsByIdMessages>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConversationsByIdMessages<
    TData = Awaited<ReturnType<typeof getConversationsByIdMessages>>,
    TError = ErrorResponse,
>(
    id: string,
    params: GetConversationsByIdMessagesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversationsByIdMessages>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getConversationsByIdMessages>>,
                    TError,
                    Awaited<ReturnType<typeof getConversationsByIdMessages>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetConversationsByIdMessages<
    TData = Awaited<ReturnType<typeof getConversationsByIdMessages>>,
    TError = ErrorResponse,
>(
    id: string,
    params: GetConversationsByIdMessagesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversationsByIdMessages>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetConversationsByIdMessages<
    TData = Awaited<ReturnType<typeof getConversationsByIdMessages>>,
    TError = ErrorResponse,
>(
    id: string,
    params: GetConversationsByIdMessagesParams,
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getConversationsByIdMessages>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetConversationsByIdMessagesQueryOptions(
        id,
        params,
        options
    );

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Sends a text message to a conversation the authenticated user takes part in
 */
export const getPostConversationsByIdMessagesUrl = (id: string) => {
    return `/conversations/${id}/messages`;
};

export const postConversationsByIdMessages = async (
    id: string,
    sendMessageBody: SendMessageBody,
    options?: RequestInit
): Promise<Message> => {
    return apiFetcher<Message>(getPostConversationsByIdMessagesUrl(id), {
        ...options,
        method: "POST",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(sendMessageBody),
    });
};

export const getPostConversationsByIdMessagesMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof postConversationsByIdMessages>>,
        TError,
        { id: string; data: SendMessageBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof postConversationsByIdMessages>>,
    TError,
    { id: string; data: SendMessageBody },
    TContext
> => {
    const mutationKey = ["postConversationsByIdMessages"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof postConversationsByIdMessages>>,
        { id: string; data: SendMessageBody }
    > = (props) => {
        const { id, data } = props ?? {};

        return postConversationsByIdMessages(id, data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PostConversationsByIdMessagesMutationResult = NonNullable<
    Awaited<ReturnType<typeof postConversationsByIdMessages>>
>;
export type PostConversationsByIdMessagesMutationBody = SendMessageBody;
export type PostConversationsByIdMessagesMutationError = ErrorResponse;

export const usePostConversationsByIdMessages = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof postConversationsByIdMessages>>,
            TError,
            { id: string; data: SendMessageBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof postConversationsByIdMessages>>,
    TError,
    { id: string; data: SendMessageBody },
    TContext
> => {
    const mutationOptions =
        getPostConversationsByIdMessagesMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Marks the conversation as read up to now for the authenticated participant
 */
export const getPatchConversationsByIdReadUrl = (id: string) => {
    return `/conversations/${id}/read`;
};

export const patchConversationsByIdRead = async (
    id: string,
    options?: RequestInit
): Promise<ConversationReadResponse> => {
    return apiFetcher<ConversationReadResponse>(
        getPatchConversationsByIdReadUrl(id),
        {
            ...options,
            method: "PATCH",
        }
    );
};

export const getPatchConversationsByIdReadMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchConversationsByIdRead>>,
        TError,
        { id: string },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchConversationsByIdRead>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationKey = ["patchConversationsByIdRead"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchConversationsByIdRead>>,
        { id: string }
    > = (props) => {
        const { id } = props ?? {};

        return patchConversationsByIdRead(id, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchConversationsByIdReadMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchConversationsByIdRead>>
>;

export type PatchConversationsByIdReadMutationError = ErrorResponse;

export const usePatchConversationsByIdRead = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchConversationsByIdRead>>,
            TError,
            { id: string },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchConversationsByIdRead>>,
    TError,
    { id: string },
    TContext
> => {
    const mutationOptions =
        getPatchConversationsByIdReadMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
