/**
 * Generated by orval v7.21.0 🍺
 * Do not edit manually.
 * Waymate API
 * Carpooling backend powering the Waymate web app.
 * OpenAPI spec version: 0.1.0
 */
import { useMutation, useQuery } from "@tanstack/react-query";
import type {
    DataTag,
    DefinedInitialDataOptions,
    DefinedUseQueryResult,
    MutationFunction,
    QueryClient,
    QueryFunction,
    QueryKey,
    UndefinedInitialDataOptions,
    UseMutationOptions,
    UseMutationResult,
    UseQueryOptions,
    UseQueryResult,
} from "@tanstack/react-query";

import type {
    ErrorResponse,
    OnboardingUserBody,
    UpdateUserBody,
    User,
} from ".././model";

import { apiFetcher } from "../../lib/api-fetcher";

type SecondParameter<T extends (...args: never) => unknown> = Parameters<T>[1];

/**
 * Returns the current user data
 */
export const getGetUsersMeUrl = () => {
    return `/users/me`;
};

export const getUsersMe = async (options?: RequestInit): Promise<User> => {
    return apiFetcher<User>(getGetUsersMeUrl(), {
        ...options,
        method: "GET",
    });
};

export const getGetUsersMeQueryKey = () => {
    return [`/users/me`] as const;
};

export const getGetUsersMeQueryOptions = <
    TData = Awaited<ReturnType<typeof getUsersMe>>,
    TError = ErrorResponse,
>(options?: {
    query?: Partial<
        UseQueryOptions<Awaited<ReturnType<typeof getUsersMe>>, TError, TData>
    >;
    request?: SecondParameter<typeof apiFetcher>;
}) => {
    const { query: queryOptions, request: requestOptions } = options ?? {};

    const queryKey = queryOptions?.queryKey ?? getGetUsersMeQueryKey();

    const queryFn: QueryFunction<Awaited<ReturnType<typeof getUsersMe>>> = () =>
        getUsersMe(requestOptions);

    return { queryKey, queryFn, ...queryOptions } as UseQueryOptions<
        Awaited<ReturnType<typeof getUsersMe>>,
        TError,
        TData
    > & { queryKey: DataTag<QueryKey, TData, TError> };
};

export type GetUsersMeQueryResult = NonNullable<
    Awaited<ReturnType<typeof getUsersMe>>
>;
export type GetUsersMeQueryError = ErrorResponse;

export function useGetUsersMe<
    TData = Awaited<ReturnType<typeof getUsersMe>>,
    TError = ErrorResponse,
>(
    options: {
        query: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUsersMe>>,
                TError,
                TData
            >
        > &
            Pick<
                DefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getUsersMe>>,
                    TError,
                    Awaited<ReturnType<typeof getUsersMe>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): DefinedUseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMe<
    TData = Awaited<ReturnType<typeof getUsersMe>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUsersMe>>,
                TError,
                TData
            >
        > &
            Pick<
                UndefinedInitialDataOptions<
                    Awaited<ReturnType<typeof getUsersMe>>,
                    TError,
                    Awaited<ReturnType<typeof getUsersMe>>
                >,
                "initialData"
            >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};
export function useGetUsersMe<
    TData = Awaited<ReturnType<typeof getUsersMe>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUsersMe>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
};

export function useGetUsersMe<
    TData = Awaited<ReturnType<typeof getUsersMe>>,
    TError = ErrorResponse,
>(
    options?: {
        query?: Partial<
            UseQueryOptions<
                Awaited<ReturnType<typeof getUsersMe>>,
                TError,
                TData
            >
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseQueryResult<TData, TError> & {
    queryKey: DataTag<QueryKey, TData, TError>;
} {
    const queryOptions = getGetUsersMeQueryOptions(options);

    const query = useQuery(queryOptions, queryClient) as UseQueryResult<
        TData,
        TError
    > & { queryKey: DataTag<QueryKey, TData, TError> };

    query.queryKey = queryOptions.queryKey;

    return query;
}

/**
 * Updates user data during onboarding
 */
export const getPatchUsersMeOnboardingUrl = () => {
    return `/users/me/onboarding`;
};

export const patchUsersMeOnboarding = async (
    onboardingUserBody: OnboardingUserBody,
    options?: RequestInit
): Promise<User> => {
    return apiFetcher<User>(getPatchUsersMeOnboardingUrl(), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(onboardingUserBody),
    });
};

export const getPatchUsersMeOnboardingMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchUsersMeOnboarding>>,
        TError,
        { data: OnboardingUserBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchUsersMeOnboarding>>,
    TError,
    { data: OnboardingUserBody },
    TContext
> => {
    const mutationKey = ["patchUsersMeOnboarding"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchUsersMeOnboarding>>,
        { data: OnboardingUserBody }
    > = (props) => {
        const { data } = props ?? {};

        return patchUsersMeOnboarding(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchUsersMeOnboardingMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchUsersMeOnboarding>>
>;
export type PatchUsersMeOnboardingMutationBody = OnboardingUserBody;
export type PatchUsersMeOnboardingMutationError = ErrorResponse;

export const usePatchUsersMeOnboarding = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchUsersMeOnboarding>>,
            TError,
            { data: OnboardingUserBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchUsersMeOnboarding>>,
    TError,
    { data: OnboardingUserBody },
    TContext
> => {
    const mutationOptions = getPatchUsersMeOnboardingMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
/**
 * Updates the current user's profile
 */
export const getPatchUsersMeProfileUrl = () => {
    return `/users/me/profile`;
};

export const patchUsersMeProfile = async (
    updateUserBody: UpdateUserBody,
    options?: RequestInit
): Promise<User> => {
    return apiFetcher<User>(getPatchUsersMeProfileUrl(), {
        ...options,
        method: "PATCH",
        headers: { "Content-Type": "application/json", ...options?.headers },
        body: JSON.stringify(updateUserBody),
    });
};

export const getPatchUsersMeProfileMutationOptions = <
    TError = ErrorResponse,
    TContext = unknown,
>(options?: {
    mutation?: UseMutationOptions<
        Awaited<ReturnType<typeof patchUsersMeProfile>>,
        TError,
        { data: UpdateUserBody },
        TContext
    >;
    request?: SecondParameter<typeof apiFetcher>;
}): UseMutationOptions<
    Awaited<ReturnType<typeof patchUsersMeProfile>>,
    TError,
    { data: UpdateUserBody },
    TContext
> => {
    const mutationKey = ["patchUsersMeProfile"];
    const { mutation: mutationOptions, request: requestOptions } = options
        ? options.mutation &&
          "mutationKey" in options.mutation &&
          options.mutation.mutationKey
            ? options
            : { ...options, mutation: { ...options.mutation, mutationKey } }
        : { mutation: { mutationKey }, request: undefined };

    const mutationFn: MutationFunction<
        Awaited<ReturnType<typeof patchUsersMeProfile>>,
        { data: UpdateUserBody }
    > = (props) => {
        const { data } = props ?? {};

        return patchUsersMeProfile(data, requestOptions);
    };

    return { mutationFn, ...mutationOptions };
};

export type PatchUsersMeProfileMutationResult = NonNullable<
    Awaited<ReturnType<typeof patchUsersMeProfile>>
>;
export type PatchUsersMeProfileMutationBody = UpdateUserBody;
export type PatchUsersMeProfileMutationError = ErrorResponse;

export const usePatchUsersMeProfile = <
    TError = ErrorResponse,
    TContext = unknown,
>(
    options?: {
        mutation?: UseMutationOptions<
            Awaited<ReturnType<typeof patchUsersMeProfile>>,
            TError,
            { data: UpdateUserBody },
            TContext
        >;
        request?: SecondParameter<typeof apiFetcher>;
    },
    queryClient?: QueryClient
): UseMutationResult<
    Awaited<ReturnType<typeof patchUsersMeProfile>>,
    TError,
    { data: UpdateUserBody },
    TContext
> => {
    const mutationOptions = getPatchUsersMeProfileMutationOptions(options);

    return useMutation(mutationOptions, queryClient);
};
